// resources/js/pages/Cajas/ComponenteDinamico/Create.vue
<script setup lang="ts">
import AppLayout from '@/layouts/AppLayoutTemplate.vue'
import { router, usePage } from '@inertiajs/vue3'
import { ref, onMounted } from 'vue'
import { Input } from '@/components/ui/input'
import { SelectRadix } from '@/components/ui/select'

type Props = {
    formulario?: { id: number; name: string; title: string }
    formularios?: Array<{ id: number; name: string; title: string }>
}

const props = defineProps<Props>()
const { props: pageProps } = usePage()

const loading = ref(false)
const successOpen = ref(false)
const successMsg = ref('')
const errors = ref<Record<string, string>>({})
const formPickerOpen = ref(false)
const formPickerQuery = ref('')
const formPickerModule = ref('')
const selectedFormulario = ref(props.formulario ?? null)
const rows = ref<Array<{ id: number; name: string; title: string }>>(props.formularios || [])
const loadingPicker = ref(false)
const page = ref(1)
const pager = ref<{ current_page: number; last_page: number; per_page: number; total: number } | null>(null)

const typeOptions = [
    { value: 'input', label: 'Input' },
    { value: 'select', label: 'Select' },
    { value: 'textarea', label: 'Textarea' },
    { value: 'checkbox', label: 'Checkbox' },
    { value: 'radio', label: 'Radio' },
    { value: 'date', label: 'Date' },
    { value: 'number', label: 'Number' },
    { value: 'email', label: 'Email' },
    { value: 'password', label: 'Password' },
]

const formTypeOptions = [
    { value: 'text', label: 'Text' },
    { value: 'email', label: 'Email' },
    { value: 'number', label: 'Number' },
    { value: 'password', label: 'Password' },
    { value: 'date', label: 'Date' },
    { value: 'tel', label: 'Telephone' },
]

onMounted(() => {
    const flash = (pageProps.value as any)?.flash
    const msg = flash?.success as string | undefined
    if (msg && typeof msg === 'string') {
        successMsg.value = msg
        successOpen.value = true
    }
})

const formData = ref({
    name: '',
    label: '',
    type: 'input',
    form_type: 'text',
    placeholder: '',
    default_value: '',
    help_text: '',
    is_required: false,
    is_disabled: false,
    is_readonly: false,
    group_id: null as number | null,
    order: null as number | null,
    data_source: null as string | null,
    event_config: null as string | null
})

const handleSubmit = async () => {
    loading.value = true
    errors.value = {}

    try {
        await router.post('/cajas/componente-dinamico', {
            ...formData.value,
            formulario_id: selectedFormulario.value ? selectedFormulario.value.id : null
        })
    } catch (error: any) {
        if (error.response?.data?.errors) {
            errors.value = error.response.data.errors
        }
    } finally {
        loading.value = false
    }
}

const handleCancel = () => {
    router.visit('/cajas/componente-dinamico')
}
</script>

<template>
  <AppLayout title="Crear Componente Dinámico">
    <div class="bg-white shadow overflow-hidden sm:rounded-md m-2">
      <div class="px-4 py-5 sm:px-6">
        <div class="flex justify-between items-center">
          <div>
            <h3 class="text-lg leading-6 font-medium text-gray-900">Crear Nuevo Componente</h3>
            <p class="mt-1 max-w-2xl text-sm text-gray-500">Define las propiedades y configuración del componente dinámico</p>
            <p v-if="selectedFormulario" class="mt-2 text-sm text-blue-600">Para el formulario: <strong>{{ selectedFormulario.title }}</strong></p>
            <p v-else class="mt-2 text-sm text-gray-500">Sin formulario asignado</p>
          </div>
          <div class="flex gap-2">
            <button @click="handleCancel" class="inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50">
              Cancelar
            </button>
            <button @click="formPickerOpen = true" class="inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50">
              {{ selectedFormulario ? 'Cambiar Formulario' : 'Elegir Formulario' }}
            </button>
          </div>
        </div>
      </div>

      <div class="px-4 py-5 sm:px-6">
        <form @submit.prevent="handleSubmit" class="space-y-4">
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label for="name" class="block text-sm font-medium text-gray-700">Nombre *</label>
              <Input id="name" v-model="formData.name" class="mt-1 w-full" required />
              <p v-if="errors.name" class="mt-1 text-xs text-red-600">{{ errors.name }}</p>
            </div>
            <div>
              <label for="label" class="block text-sm font-medium text-gray-700">Etiqueta *</label>
              <Input id="label" v-model="formData.label" class="mt-1 w-full" required />
              <p v-if="errors.label" class="mt-1 text-xs text-red-600">{{ errors.label }}</p>
            </div>
            <div>
              <label for="type" class="block text-sm font-medium text-gray-700">Tipo</label>
              <SelectRadix v-model="formData.type" :options="typeOptions" class="mt-1 w-full" />
            </div>
            <div>
              <label for="form_type" class="block text-sm font-medium text-gray-700">Tipo de Formulario</label>
              <SelectRadix v-model="formData.form_type" :options="formTypeOptions" class="mt-1 w-full" />
            </div>
            <div>
              <label for="placeholder" class="block text-sm font-medium text-gray-700">Placeholder</label>
              <Input id="placeholder" v-model="formData.placeholder" class="mt-1 w-full" />
            </div>
            <div>
              <label for="default_value" class="block text-sm font-medium text-gray-700">Valor por Defecto</label>
              <Input id="default_value" v-model="formData.default_value" class="mt-1 w-full" />
            </div>
            <div>
              <label for="group_id" class="block text-sm font-medium text-gray-700">Grupo</label>
              <Input id="group_id" v-model="formData.group_id" type="number" class="mt-1 w-full" />
            </div>
            <div>
              <label for="order" class="block text-sm font-medium text-gray-700">Orden</label>
              <Input id="order" v-model="formData.order" type="number" class="mt-1 w-full" />
            </div>
          </div>

          <div>
            <label for="help_text" class="block text-sm font-medium text-gray-700">Texto de Ayuda</label>
            <Input id="help_text" v-model="formData.help_text" class="mt-1 w-full" />
          </div>

          <div class="flex items-center gap-6">
            <label class="inline-flex items-center">
              <input type="checkbox" v-model="formData.is_required" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded" />
              <span class="ml-2 text-sm text-gray-700">Requerido</span>
            </label>
            <label class="inline-flex items-center">
              <input type="checkbox" v-model="formData.is_disabled" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded" />
              <span class="ml-2 text-sm text-gray-700">Deshabilitado</span>
            </label>
            <label class="inline-flex items-center">
              <input type="checkbox" v-model="formData.is_readonly" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded" />
              <span class="ml-2 text-sm text-gray-700">Solo Lectura</span>
            </label>
          </div>

          <div class="flex justify-end gap-3 pt-4">
            <button type="submit" :disabled="loading" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50">
              {{ loading ? 'Guardando...' : 'Guardar Componente' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </AppLayout>
</template>

// resources/js/pages/Cajas/ComponenteDinamico/Create.tsx
import { useEffect, useState } from 'react';
import { router, usePage } from '@inertiajs/react';
import AppLayout from '@/layouts/app-layout';
import { ComponentForm, ActionButtons } from '@/components/atomic';
import type { Formulario as FormularioType, Componente } from '@/types/cajas';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter, DialogClose } from '@/components/ui/dialog';

interface Props {
    formulario?: Pick<FormularioType, 'id' | 'name' | 'title'>;
    formularios?: Array<Pick<FormularioType, 'id' | 'name' | 'title'>>;
}

// Tipado local alineado con ComponentForm (estructura esperada)
type ComponentData = {
    name: string;
    type: Componente['type'];
    label: string;
    placeholder: string;
    form_type: Componente['form_type'];
    group_id: number;
    order: number;
    default_value: string;
    is_disabled: boolean;
    is_readonly: boolean;
    data_source: Array<{ value: string; label: string }>;
    css_classes: string;
    help_text: string;
    target: number;
    event_config: Record<string, string | number | boolean | null>;
    search_type: string;
    date_max: string;
    number_min: number;
    number_max: number;
    number_step: number;
};

export default function Create({ formulario, formularios = [] }: Props) {
    const { props } = usePage<{ flash?: { success?: string; error?: string } }>();

    const [loading, setLoading] = useState(false);
    const [successOpen, setSuccessOpen] = useState(false);
    const [successMsg, setSuccessMsg] = useState('');
    const [errors, setErrors] = useState<Record<string, string>>({});
    const [formPickerOpen, setFormPickerOpen] = useState(false);
    const [formPickerQuery, setFormPickerQuery] = useState('');
    const [formPickerModule, setFormPickerModule] = useState('');
    const [selectedFormulario, setSelectedFormulario] = useState<Pick<FormularioType, 'id' | 'name' | 'title'> | null>(formulario ?? null);
    const [rows, setRows] = useState<Array<Pick<FormularioType, 'id' | 'name' | 'title'>>>(formularios);
    const [loadingPicker, setLoadingPicker] = useState(false);
    const [page, setPage] = useState(1);
    const [pager, setPager] = useState<{ current_page: number; last_page: number; per_page: number; total: number } | null>(null);

    useEffect(() => {
        if (!formPickerOpen) return;
        const controller = new AbortController();
        const load = async () => {
            setLoadingPicker(true);
            try {
                const params = new URLSearchParams();
                if (formPickerQuery.trim() !== '') params.set('q', formPickerQuery.trim());
                if (formPickerModule.trim() !== '') params.set('module', formPickerModule.trim());
                params.set('per_page', '10');
                params.set('page', String(page));
                const res = await fetch(`/cajas/formulario-dinamico/options?${params.toString()}`, {
                    signal: controller.signal,
                    headers: { Accept: 'application/json' },
                });
                const json = (await res.json()) as { data: Array<Pick<FormularioType, 'id' | 'name' | 'title'>>; meta?: { current_page: number; last_page: number; per_page: number; total: number } };
                setRows(json.data || []);
                if (json.meta) setPager(json.meta);
            } catch {
                // noop
            } finally {
                setLoadingPicker(false);
            }
        };
        load();
        return () => controller.abort();
    }, [formPickerOpen, formPickerQuery, formPickerModule, page]);

     useEffect(() => {
        const msg = props?.flash?.success as string | undefined;
        if (msg && typeof msg === 'string') {
            setSuccessMsg(msg);
            setSuccessOpen(true);
        }
    }, [props]);

    const handleSubmit = async (data: ComponentData) => {
        setLoading(true);
        setErrors({});

        try {
            await router.post('/cajas/componente-dinamico', {
                ...data,
                formulario_id: selectedFormulario ? selectedFormulario.id : null,
            });
        } catch (error: unknown) {
            if (error && typeof error === 'object' && 'response' in error) {
                const axiosError = error as { response?: { data?: { errors?: Record<string, string> } } };
                if (axiosError.response?.data?.errors) {
                    setErrors(axiosError.response.data.errors);
                }
            }
        } finally {
            setLoading(false);
        }
    };

    const handleCancel = () => {
        router.visit('/cajas/componente-dinamico');
    };

    return (
        <AppLayout title="Crear Componente Dinámico">
            <Dialog open={successOpen} onOpenChange={setSuccessOpen}>
                <DialogContent>
                    <DialogHeader>
                        <DialogTitle>Actualización exitosa</DialogTitle>
                        <DialogDescription>{successMsg || 'Cambios guardados correctamente.'}</DialogDescription>
                    </DialogHeader>
                    <DialogFooter>
                        <DialogClose asChild>
                            <button
                                type="button"
                                className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700"
                            >
                                Cerrar
                            </button>
                        </DialogClose>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
            <div className="bg-white shadow overflow-hidden sm:rounded-md m-2">
                <div className="bg-white shadow overflow-hidden sm:rounded-md">
                    <div className="px-4 py-5 sm:px-6">
                        <div className="flex justify-between items-center">
                            <div>
                                <h3 className="text-lg leading-6 font-medium text-gray-900">
                                    Crear Nuevo Componente
                                </h3>
                                <p className="mt-1 max-w-2xl text-sm text-gray-500">
                                    Define las propiedades y configuración del componente dinámico
                                </p>
                                {selectedFormulario ? (
                                    <p className="mt-2 text-sm text-blue-600">
                                        Para el formulario: <strong>{selectedFormulario.title}</strong>
                                    </p>
                                ) : (
                                    <p className="mt-2 text-sm text-gray-500">Sin formulario asignado</p>
                                )}
                            </div>
                            <ActionButtons
                                actions={[
                                    {
                                        label: 'Cancelar',
                                        onClick: handleCancel,
                                        variant: 'secondary'
                                    },
                                    {
                                        label: selectedFormulario ? 'Cambiar Formulario' : 'Elegir Formulario',
                                        onClick: () => setFormPickerOpen(true),
                                        variant: 'secondary'
                                    },
                                ]}
                            />
                        </div>
                        {pager && pager.last_page > 1 && (
                            <div className="flex items-center justify-between pt-2">
                                <button
                                    type="button"
                                    disabled={page <= 1 || loadingPicker}
                                    onClick={() => setPage(p => Math.max(1, p - 1))}
                                    className="px-3 py-1 text-sm rounded border bg-white disabled:opacity-50"
                                >
                                    Anterior
                                </button>
                                <span className="text-xs text-gray-500">
                                    Página {pager.current_page} de {pager.last_page}
                                </span>
                                <button
                                    type="button"
                                    disabled={page >= pager.last_page || loadingPicker}
                                    onClick={() => setPage(p => p + 1)}
                                    className="px-3 py-1 text-sm rounded border bg-white disabled:opacity-50"
                                >
                                    Siguiente
                                </button>
                            </div>
                        )}
                    </div>

                    <div className="px-4 py-5 sm:px-6">
                        <ComponentForm
                            initialData={{}}
                            onSubmit={handleSubmit}
                            onCancel={handleCancel}
                            loading={loading}
                            errors={errors}
                        />
                    </div>
                </div>
            </div>
            {/* Picker de formulario */}
            <Dialog open={formPickerOpen} onOpenChange={setFormPickerOpen}>
                <DialogContent>
                    <DialogHeader>
                        <DialogTitle>Seleccionar formulario</DialogTitle>
                        <DialogDescription>
                            Busca y selecciona un formulario al que pertenezca este componente.
                        </DialogDescription>
                    </DialogHeader>
                    <div className="space-y-3">
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                            <input
                                type="text"
                                value={formPickerQuery}
                                onChange={(e) => { setPage(1); setFormPickerQuery(e.target.value); }}
                                placeholder="Buscar por nombre o título..."
                                className="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2"
                            />
                            <input
                                type="text"
                                value={formPickerModule}
                                onChange={(e) => { setPage(1); setFormPickerModule(e.target.value); }}
                                placeholder="Filtrar por módulo (opcional)"
                                className="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2"
                            />
                        </div>
                        <div className="max-h-64 overflow-auto divide-y divide-gray-200 rounded border">
                            {loadingPicker && (
                                <div className="p-3 text-sm text-gray-500">Cargando...</div>
                            )}
                            {!loadingPicker && rows.map((f) => (
                                <div key={f.id} className="flex items-center justify-between px-3 py-2 hover:bg-gray-50">
                                    <div>
                                        <div className="text-sm font-medium text-gray-900">{f.title}</div>
                                        <div className="text-xs text-gray-500">{f.name}</div>
                                    </div>
                                    <button
                                        type="button"
                                        onClick={() => {
                                            setSelectedFormulario(f);
                                            setFormPickerOpen(false);
                                        }}
                                        className="inline-flex items-center px-3 py-1 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700"
                                    >
                                        Seleccionar
                                    </button>
                                </div>
                            ))}
                            {!loadingPicker && rows.length === 0 && (
                                <div className="p-3 text-sm text-gray-500">No se encontraron resultados.</div>
                            )}
                        </div>
                    </div>
                    <DialogFooter>
                        <DialogClose asChild>
                            <button
                                type="button"
                                className="inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50"
                            >
                                Cerrar
                            </button>
                        </DialogClose>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </AppLayout>
    );
}
