// resources/js/pages/Cajas/FormularioDinamico/Create.tsx
import AppLayout from '@/layouts/AppLayoutTemplate';
import { Link, router } from '@inertiajs/react';
import { useState } from 'react';

export default function Create() {
    const [formData, setFormData] = useState({
        name: '',
        title: '',
        description: '',
        module: '',
        endpoint: '',
        method: 'POST',
        is_active: true,
        layout_config: {
            columns: 1,
            spacing: 'md',
            theme: 'default'
        },
        permissions: {
            public: false,
            roles: []
        }
    });

    const [errors, setErrors] = useState<Record<string, string>>({});
    const [processing, setProcessing] = useState(false);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        const { name, value, type } = e.target;
        const checked = (e.target as HTMLInputElement).checked;

        setFormData(prev => ({
            ...prev,
            [name]: type === 'checkbox' ? checked : value
        }));

        // Limpiar error cuando el usuario comienza a escribir
        if (errors[name]) {
            setErrors(prev => ({
                ...prev,
                [name]: ''
            }));
        }
    };

    const handleJsonChange = (field: string, value: any) => {
        setFormData(prev => ({
            ...prev,
            [field]: value
        }));
    };

    const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        setProcessing(true);
        console.log(formData);
        router.post(
            '/cajas/formulario-dinamico',
            {
                ...formData,
                layout_config: JSON.stringify(formData.layout_config),
                permissions: JSON.stringify(formData.permissions),
            },
            {
                onError: (errs: Record<string, string>) => {
                    setErrors(errs);
                },
                onFinish: () => {
                    setProcessing(false);
                },
            }
        );
    };

    return (
        <AppLayout title="Crear Formulario Dinámico">
            <div className="bg-white shadow overflow-hidden sm:rounded-md">
                <div className="px-4 py-5 sm:px-6 flex justify-between items-center">
                    <div>
                        <h3 className="text-lg leading-6 font-medium text-gray-900">
                            Crear Formulario Dinámico
                        </h3>
                        <p className="mt-1 max-w-2xl text-sm text-gray-500">
                            Formulario para crear un nuevo formulario dinámico
                        </p>
                    </div>
                    <Link
                        href="/cajas/formulario-dinamico"
                        className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700"
                    >
                        Volver
                    </Link>
                </div>
                <div className="px-4 py-5 sm:px-6">
                    <form onSubmit={handleSubmit}>
                        <div className="grid grid-cols-6 gap-6">
                            <div className="col-span-6 sm:col-span-3">
                                <label htmlFor="name" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Nombre único *</label>
                                <input
                                    type="text"
                                    name="name"
                                    id="name"
                                    required
                                    className={`mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2 ${errors.name ? 'border-red-300' : ''}`}
                                    value={formData.name}
                                    onChange={handleChange}
                                />
                                {errors.name && (<p className="mt-1 text-sm text-red-600">{errors.name}</p>)}
                                <p className="mt-1 text-xs text-gray-500">Identificador único para el formulario (ej: formulario_registro)</p>
                            </div>

                            <div className="col-span-6 sm:col-span-3">
                                <label htmlFor="title" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Título *</label>
                                <input
                                    type="text"
                                    name="title"
                                    id="title"
                                    required
                                    className={`mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2 ${errors.title ? 'border-red-300' : ''}`}
                                    value={formData.title}
                                    onChange={handleChange}
                                />
                                {errors.title && (<p className="mt-1 text-sm text-red-600">{errors.title}</p>)}
                                <p className="mt-1 text-xs text-gray-500">Título visible del formulario</p>
                            </div>

                            <div className="col-span-6">
                                <label htmlFor="description" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Descripción</label>
                                <textarea
                                    name="description"
                                    id="description"
                                    rows={3}
                                    className={`mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2 ${errors.description ? 'border-red-300' : ''}`}
                                    value={formData.description}
                                    onChange={handleChange}
                                />
                                {errors.description && (<p className="mt-1 text-sm text-red-600">{errors.description}</p>)}
                                <p className="mt-1 text-xs text-gray-500">Descripción opcional del formulario</p>
                            </div>

                            <div className="col-span-6 sm:col-span-2">
                                <label htmlFor="module" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Módulo *</label>
                                <input
                                    type="text"
                                    name="module"
                                    id="module"
                                    required
                                    className={`mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2 ${errors.module ? 'border-red-300' : ''}`}
                                    value={formData.module}
                                    onChange={handleChange}
                                />
                                {errors.module && (<p className="mt-1 text-sm text-red-600">{errors.module}</p>)}
                                <p className="mt-1 text-xs text-gray-500">Módulo al que pertenece (ej: auth, creditos)</p>
                            </div>

                            <div className="col-span-6 sm:col-span-2">
                                <label htmlFor="endpoint" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Endpoint *</label>
                                <input
                                    type="text"
                                    name="endpoint"
                                    id="endpoint"
                                    required
                                    className={`mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2 ${errors.endpoint ? 'border-red-300' : ''}`}
                                    value={formData.endpoint}
                                    onChange={handleChange}
                                />
                                {errors.endpoint && (<p className="mt-1 text-sm text-red-600">{errors.endpoint}</p>)}
                                <p className="mt-1 text-xs text-gray-500">URL del endpoint API</p>
                            </div>

                            <div className="col-span-6 sm:col-span-2">
                                <label htmlFor="method" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Método HTTP *</label>
                                <select
                                    name="method"
                                    id="method"
                                    className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2"
                                    value={formData.method}
                                    onChange={handleChange}
                                >
                                    <option value="GET">GET</option>
                                    <option value="POST">POST</option>
                                    <option value="PUT">PUT</option>
                                    <option value="PATCH">PATCH</option>
                                    <option value="DELETE">DELETE</option>
                                </select>
                                <p className="mt-1 text-xs text-gray-500">Método HTTP para el endpoint</p>
                            </div>

                            <div className="col-span-6 sm:col-span-3">
                                <label htmlFor="is_active" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Estado</label>
                                <div className="mt-1">
                                    <label className="inline-flex items-center">
                                        <input
                                            type="checkbox"
                                            name="is_active"
                                            id="is_active"
                                            className="rounded border-gray-300 text-indigo-600 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                            checked={formData.is_active}
                                            onChange={handleChange}
                                        />
                                        <span className="ml-2 text-sm text-gray-700">Activo</span>
                                    </label>
                                </div>
                                <p className="mt-1 text-xs text-gray-500">Si el formulario está activo y disponible</p>
                            </div>

                            <div className="col-span-6">
                                <div className="border-t border-gray-200 pt-6">
                                    <h4 className="text-sm font-medium text-gray-900 mb-4">Configuración de Layout</h4>
                                    <div className="grid grid-cols-3 gap-4">
                                        <div>
                                            <label className="block text-sm font-medium text-gray-700">Columnas</label>
                                            <select
                                                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2"
                                                value={formData.layout_config.columns}
                                                onChange={(e) => handleJsonChange('layout_config', { ...formData.layout_config, columns: Number(e.target.value) })}
                                            >
                                                <option value={1}>1 Columna</option>
                                                <option value={2}>2 Columnas</option>
                                                <option value={3}>3 Columnas</option>
                                            </select>
                                        </div>
                                        <div>
                                            <label className="block text-sm font-medium text-gray-700">Espaciado</label>
                                            <select
                                                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2"
                                                value={formData.layout_config.spacing}
                                                onChange={(e) => handleJsonChange('layout_config', { ...formData.layout_config, spacing: e.target.value })}
                                            >
                                                <option value="sm">Pequeño</option>
                                                <option value="md">Mediano</option>
                                                <option value="lg">Grande</option>
                                            </select>
                                        </div>
                                        <div>
                                            <label className="block text-sm font-medium text-gray-700">Tema</label>
                                            <select
                                                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2"
                                                value={formData.layout_config.theme}
                                                onChange={(e) => handleJsonChange('layout_config', { ...formData.layout_config, theme: e.target.value })}
                                            >
                                                <option value="default">Por defecto</option>
                                                <option value="professional">Profesional</option>
                                                <option value="clean">Limpio</option>
                                                <option value="support">Soporte</option>
                                                <option value="feedback">Feedback</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div className="col-span-6">
                                <div className="border-t border-gray-200 pt-6">
                                    <h4 className="text-sm font-medium text-gray-900 mb-4">Permisos</h4>
                                    <div className="space-y-4">
                                        <div>
                                            <label className="inline-flex items-center">
                                                <input
                                                    type="checkbox"
                                                    className="rounded border-gray-300 text-indigo-600 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                                    checked={formData.permissions.public}
                                                    onChange={(e) => handleJsonChange('permissions', { ...formData.permissions, public: e.target.checked })}
                                                />
                                                <span className="ml-2 text-sm text-gray-700">Público (accesible sin autenticación)</span>
                                            </label>
                                        </div>
                                        {!formData.permissions.public && (
                                            <div>
                                                <label className="block text-sm font-medium text-gray-700 mb-2">Roles permitidos</label>
                                                <div className="grid grid-cols-2 gap-2">
                                                    {['cliente', 'asesor', 'admin', 'usuario'].map(role => (
                                                        <label key={role} className="inline-flex items-center">
                                                            <input
                                                                type="checkbox"
                                                                className="rounded border-gray-300 text-indigo-600 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                                                checked={formData.permissions.roles.includes(role)}
                                                                onChange={(e) => {
                                                                    const roles = e.target.checked
                                                                        ? [...formData.permissions.roles, role]
                                                                        : formData.permissions.roles.filter(r => r !== role);
                                                                    handleJsonChange('permissions', { ...formData.permissions, roles });
                                                                }}
                                                            />
                                                            <span className="ml-2 text-sm text-gray-700 capitalize">{role}</span>
                                                        </label>
                                                    ))}
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="flex justify-end pt-6 border-t border-gray-200 mt-6">
                            <button
                                type="submit"
                                disabled={processing}
                                className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                                {processing ? 'Guardando...' : 'Guardar Formulario'}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </AppLayout>
    );
}

// resources/js/pages/Cajas/FormularioDinamico/Create.vue
<script setup lang="ts">
import AppLayout from '@/layouts/AppLayoutTemplate.vue'
import { Link, router } from '@inertiajs/vue3'
import { ref } from 'vue'

const formData = ref({
    name: '',
    title: '',
    description: '',
    module: '',
    endpoint: '',
    method: 'POST',
    is_active: true,
    layout_config: {
        columns: 1,
        spacing: 'md',
        theme: 'default'
    },
    permissions: {
        public: false,
        roles: [] as string[]
    }
})

const errors = ref<Record<string, string>>({})
const processing = ref(false)

const handleChange = (e: Event) => {
    const target = e.target as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    const { name, value, type } = target
    const checked = (target as HTMLInputElement).checked

    if (name.startsWith('permissions.') || name.startsWith('layout_config.')) {
        const [parent, child] = name.split('.')
        if (parent === 'permissions') {
            (formData.value.permissions as any)[child] = type === 'checkbox' ? checked : value
        } else if (parent === 'layout_config') {
            (formData.value.layout_config as any)[child] = value
        }
    } else {
        (formData.value as any)[name] = type === 'checkbox' ? checked : value
    }

    if (errors.value[name]) {
        errors.value[name] = ''
    }
}

const handleSubmit = async (event: Event) => {
    event.preventDefault()
    processing.value = true
    router.post(
        '/cajas/formulario-dinamico',
        {
            ...formData.value,
            layout_config: JSON.stringify(formData.value.layout_config),
            permissions: JSON.stringify(formData.value.permissions),
        },
        {
            onError: (errs: Record<string, string>) => {
                errors.value = errs
            },
            onFinish: () => {
                processing.value = false
            },
        }
    )
}
</script>

<template>
  <AppLayout title="Crear Formulario Dinámico">
    <div class="bg-white shadow overflow-hidden sm:rounded-md">
      <div class="px-4 py-5 sm:px-6 flex justify-between items-center">
        <div>
          <h3 class="text-lg leading-6 font-medium text-gray-900">
            Crear Formulario Dinámico
          </h3>
          <p class="mt-1 max-w-2xl text-sm text-gray-500">
            Formulario para crear un nuevo formulario dinámico
          </p>
        </div>
        <Link
          href="/cajas/formulario-dinamico"
          class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700"
        >
          Volver
        </Link>
      </div>
      <div class="px-4 py-5 sm:px-6">
        <form @submit="handleSubmit">
          <div class="grid grid-cols-6 gap-6">
            <div class="col-span-6 sm:col-span-3">
              <label for="name" class="block text-sm font-medium text-gray-700 dark:text-gray-300">Nombre único *</label>
              <input
                type="text"
                name="name"
                id="name"
                required
                :class="['mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2', errors.name ? 'border-red-300' : '']"
                v-model="formData.name"
                @input="handleChange"
              />
              <p v-if="errors.name" class="mt-1 text-sm text-red-600">{{ errors.name }}</p>
              <p class="mt-1 text-xs text-gray-500">Identificador único para el formulario</p>
            </div>

            <div class="col-span-6 sm:col-span-3">
              <label for="title" class="block text-sm font-medium text-gray-700 dark:text-gray-300">Título *</label>
              <input
                type="text"
                name="title"
                id="title"
                required
                :class="['mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2', errors.title ? 'border-red-300' : '']"
                v-model="formData.title"
                @input="handleChange"
              />
              <p v-if="errors.title" class="mt-1 text-sm text-red-600">{{ errors.title }}</p>
            </div>

            <div class="col-span-6">
              <label for="description" class="block text-sm font-medium text-gray-700 dark:text-gray-300">Descripción</label>
              <textarea
                name="description"
                id="description"
                rows="3"
                :class="['mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2', errors.description ? 'border-red-300' : '']"
                v-model="formData.description"
                @input="handleChange"
              />
              <p v-if="errors.description" class="mt-1 text-sm text-red-600">{{ errors.description }}</p>
            </div>

            <div class="col-span-6 sm:col-span-2">
              <label for="module" class="block text-sm font-medium text-gray-700 dark:text-gray-300">Módulo *</label>
              <input
                type="text"
                name="module"
                id="module"
                required
                :class="['mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2', errors.module ? 'border-red-300' : '']"
                v-model="formData.module"
                @input="handleChange"
              />
              <p v-if="errors.module" class="mt-1 text-sm text-red-600">{{ errors.module }}</p>
            </div>

            <div class="col-span-6 sm:col-span-2">
              <label for="endpoint" class="block text-sm font-medium text-gray-700 dark:text-gray-300">Endpoint *</label>
              <input
                type="text"
                name="endpoint"
                id="endpoint"
                required
                :class="['mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2', errors.endpoint ? 'border-red-300' : '']"
                v-model="formData.endpoint"
                @input="handleChange"
              />
              <p v-if="errors.endpoint" class="mt-1 text-sm text-red-600">{{ errors.endpoint }}</p>
            </div>

            <div class="col-span-6 sm:col-span-2">
              <label for="method" class="block text-sm font-medium text-gray-700 dark:text-gray-300">Método HTTP *</label>
              <select
                name="method"
                id="method"
                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2"
                v-model="formData.method"
                @change="handleChange"
              >
                <option value="GET">GET</option>
                <option value="POST">POST</option>
                <option value="PUT">PUT</option>
                <option value="PATCH">PATCH</option>
                <option value="DELETE">DELETE</option>
              </select>
            </div>

            <div class="col-span-6 sm:col-span-3">
              <label for="is_active" class="block text-sm font-medium text-gray-700 dark:text-gray-300">Estado</label>
              <div class="mt-1">
                <label class="inline-flex items-center">
                  <input
                    type="checkbox"
                    name="is_active"
                    class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded"
                    v-model="formData.is_active"
                    @change="handleChange"
                  />
                  <span class="ml-2 text-sm text-gray-600">Formulario activo</span>
                </label>
              </div>
            </div>
          </div>

          <div class="flex justify-end pt-6">
            <button
              type="submit"
              :disabled="processing"
              class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {{ processing ? 'Guardando...' : 'Guardar Formulario' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </AppLayout>
</template>
