// resources/js/components/ui/auth-background-shapes.tsx
import type React from "react"

// Componente decorativo de fondo (tres figuras). Reutilizable.
// Mantenerlo simple y configurable vía className si hiciera falta.
export default function AuthBackgroundShapes({ className = "" }: { className?: string }) {
  return (
    <div className={`pointer-events-none absolute inset-0 z-0 ${className}`.trim()} aria-hidden="true">
      <div className="absolute top-6 right-6 w-16 h-16 bg-gradient-to-br from-emerald-200 to-teal-300 rounded-2xl opacity-70"></div>
      <div className="absolute bottom-4 right-12 w-10 h-10 bg-gradient-to-tr from-emerald-300 to-green-400 rounded-lg opacity-40"></div>
      <div className="absolute top-1/3 left-3 w-13 h-13 bg-gradient-to-bl from-teal-200 to-emerald-200 rounded-full opacity-30"></div>
    </div>
  )
}

// resources/js/components/ui/auth-background-shapes/AuthBackgroundShapes.vue
<script setup lang="ts">
</script>

<template>
  <div class="absolute inset-0 -z-10 overflow-hidden">
    <svg class="h-full w-full" viewBox="0 0 100 100" preserveAspectRatio="none">
      <defs>
        <radialGradient id="grad1" cx="50%" cy="50%" r="50%">
          <stop offset="0%" style="stop-color:#10b981;stop-opacity:0.3" />
          <stop offset="100%" style="stop-color:#10b981;stop-opacity:0" />
        </radialGradient>
      </defs>
      <circle cx="20%" cy="80%" r="40" fill="url(#grad1)" />
      <circle cx="80%" cy="20%" r="35" fill="url(#grad1)" />
      <circle cx="70%" cy="70%" r="25" fill="url(#grad1)" />
      <circle cx="30%" cy="30%" r="20" fill="url(#grad1)" />
    </svg>
    <div class="absolute top-0 right-0 -mr-20 -mt-20 h-96 w-96 rounded-full bg-gradient-to-br from-emerald-200/30 to-transparent blur-3xl" />
    <div class="absolute bottom-0 left-0 -ml-20 -mb-20 h-96 w-96 rounded-full bg-gradient-to-tr from-teal-200/30 to-transparent blur-3xl" />
  </div>
</template>
