// resources/js/pages/Cajas/ComponenteDinamico/Edit.vue
<script setup lang="ts">
import AppLayout from '@/layouts/AppLayoutTemplate.vue'
import { Link, router, usePage } from '@inertiajs/vue3'
import { ref, onMounted, computed } from 'vue'
import { X } from 'lucide-vue-next'

type DataSourceItem = { value: string; label: string }

type Componente = {
  id: number
  name: string
  label: string
  type: string
  form_type?: string
  placeholder?: string
  default_value?: string
  help_text?: string
  is_required?: boolean
  is_disabled?: boolean
  is_readonly?: boolean
  group_id: number
  order: number
  css_classes?: string
  target?: number
  search_type?: string
  search_endpoint?: string
  date_max?: string
  number_min?: string | number
  number_max?: string | number
  number_step?: number
  data_source?: DataSourceItem[] | null
  event_config?: Record<string, unknown>
  formulario_id?: number
}

type Props = {
  componente: Componente
}

const props = defineProps<Props>()
const { props: pageProps } = usePage()

const formData = ref({
  name: '',
  type: 'text',
  label: '',
  placeholder: '',
  form_type: 'input',
  group_id: 1,
  order: 1,
  default_value: '',
  is_disabled: false,
  is_readonly: false,
  data_source: [] as DataSourceItem[],
  css_classes: '',
  help_text: '',
  target: -1,
  event_config: {} as Record<string, string | number | boolean | null>,
  search_type: '',
  search_endpoint: '',
  date_max: '',
  number_min: '',
  number_max: '',
  number_step: 1,
  formulario_id: undefined as number | undefined
})

const processing = ref(false)
const errors = ref<Record<string, string>>({})
const successOpen = ref(false)
const successMsg = ref('')

const showSearchType = computed(() =>
  formData.value.form_type === 'select' || formData.value.form_type === 'dialog'
)
const showAjaxEndpoint = computed(() =>
  (formData.value.form_type === 'select' || formData.value.form_type === 'dialog') &&
  formData.value.search_type === 'ajax'
)
const showDataSource = computed(() =>
  formData.value.form_type === 'select' && formData.value.search_type === 'local'
)
const showDateConfig = computed(() => formData.value.form_type === 'date')
const showNumberConfig = computed(() =>
  formData.value.form_type === 'input' && formData.value.type === 'number'
)

onMounted(() => {
  formData.value = {
    name: props.componente.name || '',
    type: (props.componente.type || 'text').toString().toLowerCase(),
    label: props.componente.label || '',
    placeholder: props.componente.placeholder || '',
    form_type: (props.componente.form_type || 'input').toString().toLowerCase(),
    group_id: props.componente.group_id || 1,
    order: props.componente.order || 1,
    default_value: props.componente.default_value || '',
    is_disabled: props.componente.is_disabled || false,
    is_readonly: props.componente.is_readonly || false,
    data_source: (props.componente.data_source as DataSourceItem[] | null) || [],
    css_classes: props.componente.css_classes || '',
    help_text: props.componente.help_text || '',
    target: props.componente.target || -1,
    event_config: (props.componente.event_config as Record<string, string | number | boolean | null>) || {},
    search_type: (props.componente.search_type as string) || '',
    search_endpoint: (props.componente.search_endpoint as string) || '',
    date_max: props.componente.date_max || '',
    number_min: props.componente.number_min?.toString() || '',
    number_max: props.componente.number_max?.toString() || '',
    number_step: props.componente.number_step || 1,
    formulario_id: props.componente.formulario_id
  }

  const msg = (pageProps.value as any)?.flash?.success as string | undefined
  if (msg) {
    successMsg.value = msg
    successOpen.value = true
  }
})

const handleChange = (e: Event) => {
  const target = e.target as HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement
  const { name, value, type } = target

  if (type === 'checkbox') {
    const checked = (target as HTMLInputElement).checked
    ;(formData.value as any)[name] = checked
  } else if (type === 'number') {
    ;(formData.value as any)[name] = Number(value)
  } else {
    ;(formData.value as any)[name] = value
  }

  if (errors.value[name]) {
    errors.value = { ...errors.value, [name]: '' }
  }
}

const handleDataSourceChange = (index: number, field: 'value' | 'label', value: string) => {
  const list = [...formData.value.data_source]
  list[index] = { ...list[index], [field]: value }
  formData.value.data_source = list
}

const addDataSourceItem = () => {
  formData.value.data_source = [...formData.value.data_source, { value: '', label: '' }]
}

const removeDataSourceItem = (index: number) => {
  formData.value.data_source = formData.value.data_source.filter((_, i) => i !== index)
}

const validate = (): boolean => {
  const v: Record<string, string> = {}
  const typeAllowed = ['text', 'number', 'date', 'email', 'phone', 'hidden']
  const formTypeAllowed = ['input', 'select', 'textarea', 'date', 'dialog', 'radio', 'checkbox', 'address']

  if (!formData.value.name.trim()) v.name = 'El nombre es obligatorio.'
  if (!formData.value.label.trim()) v.label = 'La etiqueta es obligatoria.'
  if (!typeAllowed.includes(formData.value.type)) v.type = 'Propiedad type del componente inválido.'
  if (!formTypeAllowed.includes(formData.value.form_type)) v.form_type = 'Tipo de formulario inválido.'
  if (!formData.value.group_id || Number(formData.value.group_id) < 1) v.group_id = 'Grupo debe ser un entero ≥ 1.'
  if (!formData.value.order || Number(formData.value.order) < 1) v.order = 'Orden debe ser un entero ≥ 1.'

  if (showSearchType.value) {
    const allowedSearch = ['ninguno', 'local', 'ajax', 'collection', '']
    if (!allowedSearch.includes(formData.value.search_type)) {
      v.search_type = 'Tipo de búsqueda inválido.'
    }
    if (formData.value.search_type === 'ajax') {
      if (!formData.value.search_endpoint || formData.value.search_endpoint.trim().length < 160) {
        v.search_endpoint = 'Debe especificar un endpoint (mínimo 160 caracteres).'
      }
    }
  }

  if (formData.value.form_type === 'select' && Array.isArray(formData.value.data_source) && formData.value.data_source.length > 0) {
    const invalid = formData.value.data_source.find((it) => !it.value.trim() || !it.label.trim())
    if (invalid) v.data_source = 'Todas las opciones deben tener valor y etiqueta.'
  }

  if (formData.value.type === 'number' && formData.value.form_type === 'input') {
    const step = Number(formData.value.number_step)
    if (!(step > 0)) v.number_step = 'El incremento debe ser mayor que 0.'
    const min = formData.value.number_min !== '' ? Number(formData.value.number_min) : null
    const max = formData.value.number_max !== '' ? Number(formData.value.number_max) : null
    if (min !== null && Number.isNaN(min)) v.number_min = 'Número mínimo inválido.'
    if (max !== null && Number.isNaN(max)) v.number_max = 'Número máximo inválido.'
    if (min !== null && max !== null && min > max) v.number_min = 'El mínimo no puede ser mayor que el máximo.'
  }

  if (formData.value.type === 'date' && formData.value.date_max) {
    const ts = Date.parse(formData.value.date_max)
    if (Number.isNaN(ts)) v.date_max = 'Fecha máxima inválida.'
  }

  errors.value = v
  return Object.keys(v).length === 0
}

const handleSubmit = async () => {
  if (!validate()) return

  processing.value = true

  const payload = {
    ...formData.value,
    search_type: formData.value.search_type === 'ninguno' || formData.value.search_type === '' ? null : formData.value.search_type,
    data_source: formData.value.form_type === 'select' && formData.value.search_type === 'local' ? formData.value.data_source : null,
    search_endpoint: formData.value.search_type === 'ajax' ? formData.value.search_endpoint : null,
    event_config: Object.keys(formData.value.event_config).length > 0 ? formData.value.event_config : null,
    date_max: formData.value.type === 'date' && formData.value.date_max ? formData.value.date_max : null,
    number_min: formData.value.type === 'number' && formData.value.number_min ? Number(formData.value.number_min) : null,
    number_max: formData.value.type === 'number' && formData.value.number_max ? Number(formData.value.number_max) : null,
    number_step: formData.value.type === 'number' ? Number(formData.value.number_step) : 1
  }

  try {
    router.put(`/cajas/componente-dinamico/${props.componente.id}`, payload, {
      preserveState: true,
      onSuccess: () => {
        successMsg.value = (pageProps.value as any)?.flash?.success || 'Componente actualizado correctamente.'
        successOpen.value = true
      },
      onError: (err) => {
        errors.value = err as Record<string, string>
      },
      onFinish: () => {
        processing.value = false
      }
    })
  } catch {
    processing.value = false
  }
}
</script>

<template>
  <AppLayout :title="`Editar Componente: ${componente.label}`">
    <div v-if="successOpen" class="fixed inset-0 z-50 flex items-center justify-center">
      <div class="absolute inset-0 bg-black/40" @click="successOpen = false" />
      <div class="relative bg-white rounded-lg shadow-xl w-full max-w-md mx-4 p-6">
        <div class="mb-4">
          <h3 class="text-lg font-medium text-emerald-600">Actualización exitosa</h3>
          <p class="mt-2 text-sm text-gray-500">{{ successMsg || 'Cambios guardados correctamente.' }}</p>
        </div>
        <div class="flex justify-end">
          <button
            @click="successOpen = false"
            class="px-4 py-2 text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700"
          >
            Cerrar
          </button>
        </div>
      </div>
    </div>

    <div class="bg-white shadow sm:rounded-md m-2 overflow-hidden">
      <div class="px-4 py-5 sm:px-6 flex items-center justify-between">
        <div>
          <h3 class="text-lg leading-6 font-medium text-gray-900">Editar Componente Dinámico</h3>
          <p class="mt-1 max-w-2xl text-sm text-gray-500">Modificar los datos del componente dinámico</p>
        </div>
        <div class="space-x-2 flex">
          <Link
            :href="`/cajas/componente-dinamico?formulario_id=${componente.formulario_id}`"
            class="px-4 py-2 text-sm font-medium rounded-md text-white bg-indigo-400 hover:bg-indigo-400 inline-flex items-center border border-transparent"
          >
            Volver con formulario
          </Link>
          <Link
            href="/cajas/componente-dinamico"
            class="px-4 py-2 text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 inline-flex items-center border border-transparent"
          >
            Volver
          </Link>
        </div>
      </div>

      <div class="px-4 py-5 sm:px-6">
        <form @submit.prevent="handleSubmit">
          <div class="gap-6 grid grid-cols-6">
            <div class="sm:col-span-3 col-span-6">
              <label for="name" class="text-sm font-medium text-gray-700 block">
                Nombre único *
              </label>
              <input
                type="text"
                name="name"
                id="name"
                required
                :class="['mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full', errors.name ? 'border-red-300' : '']"
                v-model="formData.name"
                @input="handleChange"
              />
              <p v-if="errors.name" class="mt-1 text-sm text-red-600">{{ errors.name }}</p>
              <p class="mt-1 text-xs text-gray-500">Identificador único para el componente</p>
            </div>

            <div class="sm:col-span-3 col-span-6">
              <label for="type" class="text-sm font-medium text-gray-700 block">
                Tipo *
              </label>
              <select
                name="type"
                id="type"
                required
                class="mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full"
                v-model="formData.type"
                @change="handleChange"
              >
                <option value="text">Texto</option>
                <option value="number">Número</option>
                <option value="date">Fecha</option>
                <option value="hidden">Oculto</option>
                <option value="phone">Teléfono</option>
                <option value="email">Email</option>
              </select>
            </div>

            <div class="sm:col-span-3 col-span-6">
              <label for="form_type" class="text-sm font-medium text-gray-700 block">
                Tipo de formulario *
              </label>
              <select
                name="form_type"
                id="form_type"
                required
                class="mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full"
                v-model="formData.form_type"
                @change="handleChange"
              >
                <option value="input">Input</option>
                <option value="select">Select</option>
                <option value="textarea">Textarea</option>
                <option value="date">Date</option>
                <option value="dialog">Dialog</option>
                <option value="radio">Radio</option>
                <option value="checkbox">Checkbox</option>
                <option value="address">Dirección</option>
              </select>
            </div>

            <div v-if="showSearchType" class="sm:col-span-3 col-span-6">
              <label for="search_type" class="text-sm font-medium text-gray-700 block">
                Tipo de búsqueda
              </label>
              <select
                name="search_type"
                id="search_type"
                class="mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full"
                v-model="formData.search_type"
                @change="handleChange"
              >
                <option value="">Seleccione</option>
                <option value="ninguno">Ninguno</option>
                <option value="local">Local</option>
                <option value="ajax">Ajax</option>
                <option value="collection">Collection</option>
              </select>
              <p v-if="errors.search_type" class="mt-1 text-sm text-red-600">{{ errors.search_type }}</p>
            </div>

            <div v-if="showAjaxEndpoint" class="col-span-6">
              <label for="search_endpoint" class="text-sm font-medium text-gray-700 block">
                Endpoint de búsqueda (AJAX)
              </label>
              <input
                type="text"
                name="search_endpoint"
                id="search_endpoint"
                minLength="160"
                :class="['mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full', errors.search_endpoint ? 'border-red-300' : '']"
                v-model="formData.search_endpoint"
                @input="handleChange"
                placeholder="https://api.midominio.com/recurso?param1=... (mínimo 160 caracteres)"
              />
              <p v-if="errors.search_endpoint" class="mt-1 text-sm text-red-600">{{ errors.search_endpoint }}</p>
            </div>

            <div class="sm:col-span-3 col-span-6">
              <label for="label" class="text-sm font-medium text-gray-700 block">
                Etiqueta *
              </label>
              <input
                type="text"
                name="label"
                id="label"
                required
                :class="['mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full', errors.label ? 'border-red-300' : '']"
                v-model="formData.label"
                @input="handleChange"
              />
              <p v-if="errors.label" class="mt-1 text-sm text-red-600">{{ errors.label }}</p>
            </div>

            <div class="sm:col-span-3 col-span-6">
              <label for="placeholder" class="text-sm font-medium text-gray-700 block">
                Placeholder
              </label>
              <input
                type="text"
                name="placeholder"
                id="placeholder"
                class="mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full"
                v-model="formData.placeholder"
                @input="handleChange"
              />
            </div>

            <div class="sm:col-span-2 col-span-6">
              <label for="group_id" class="text-sm font-medium text-gray-700 block">
                Grupo *
              </label>
              <input
                type="number"
                name="group_id"
                id="group_id"
                required
                min="1"
                :class="['mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full', errors.group_id ? 'border-red-300' : '']"
                v-model.number="formData.group_id"
                @input="handleChange"
              />
              <p v-if="errors.group_id" class="mt-1 text-sm text-red-600">{{ errors.group_id }}</p>
            </div>

            <div class="sm:col-span-2 col-span-6">
              <label for="order" class="text-sm font-medium text-gray-700 block">
                Orden *
              </label>
              <input
                type="number"
                name="order"
                id="order"
                required
                min="1"
                :class="['mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full', errors.order ? 'border-red-300' : '']"
                v-model.number="formData.order"
                @input="handleChange"
              />
              <p v-if="errors.order" class="mt-1 text-sm text-red-600">{{ errors.order }}</p>
            </div>

            <div class="sm:col-span-2 col-span-6">
              <div class="space-y-3">
                <div>
                  <label class="inline-flex items-center">
                    <input
                      type="checkbox"
                      name="is_disabled"
                      class="rounded border-gray-300 text-indigo-600 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                      v-model="formData.is_disabled"
                      @change="handleChange"
                    />
                    <span class="ml-2 text-sm text-gray-700">Deshabilitado</span>
                  </label>
                </div>
                <div>
                  <label class="inline-flex items-center">
                    <input
                      type="checkbox"
                      name="is_readonly"
                      class="rounded border-gray-300 text-indigo-600 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                      v-model="formData.is_readonly"
                      @change="handleChange"
                    />
                    <span class="ml-2 text-sm text-gray-700">Solo lectura</span>
                  </label>
                </div>
              </div>
            </div>

            <div class="sm:col-span-2 col-span-6">
              <label for="target" class="text-sm font-medium text-gray-700 block">
                Objetivo
              </label>
              <input
                type="number"
                name="target"
                id="target"
                class="mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full"
                v-model.number="formData.target"
                @input="handleChange"
              />
            </div>

            <div class="sm:col-span-3 col-span-6">
              <label for="default_value" class="text-sm font-medium text-gray-700 block">
                Valor por defecto
              </label>
              <input
                type="text"
                name="default_value"
                id="default_value"
                class="mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full"
                v-model="formData.default_value"
                @input="handleChange"
              />
            </div>

            <div class="col-span-6">
              <label for="help_text" class="text-sm font-medium text-gray-700 block">
                Texto de ayuda
              </label>
              <textarea
                name="help_text"
                id="help_text"
                rows="2"
                class="mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full"
                v-model="formData.help_text"
                @input="handleChange"
              />
            </div>

            <div class="col-span-6">
              <label for="css_classes" class="text-sm font-medium text-gray-700 block">
                Clases CSS
              </label>
              <input
                type="text"
                name="css_classes"
                id="css_classes"
                class="mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full"
                v-model="formData.css_classes"
                @input="handleChange"
              />
            </div>

            <div v-if="showDataSource" class="col-span-6">
              <div class="border-gray-200 pt-6 border-t">
                <h4 class="text-sm font-medium text-gray-900 mb-4">Opciones del Select</h4>
                <div class="space-y-3">
                  <div v-for="(item, index) in formData.data_source" :key="index" class="gap-3 flex items-end">
                    <div class="flex-1">
                      <label class="text-sm font-medium text-gray-700 block">Valor</label>
                      <input
                        type="text"
                        class="mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2 block w-full"
                        :value="item.value"
                        @input="handleDataSourceChange(index, 'value', ($event.target as HTMLInputElement).value)"
                      />
                    </div>
                    <div class="flex-1">
                      <label class="text-sm font-medium text-gray-700 block">Etiqueta</label>
                      <input
                        type="text"
                        class="mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2 block w-full"
                        :value="item.label"
                        @input="handleDataSourceChange(index, 'label', ($event.target as HTMLInputElement).value)"
                      />
                    </div>
                    <button
                      type="button"
                      @click="removeDataSourceItem(index)"
                      class="h-9 px-3 rounded-md border border-red-300 text-sm font-medium text-red-700 hover:bg-red-50 inline-flex items-center"
                    >
                      <X class="w-4 h-4" />
                    </button>
                  </div>
                  <button
                    type="button"
                    @click="addDataSourceItem"
                    class="px-3 py-2 border border-gray-300 shadow-sm text-sm leading-4 font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 inline-flex items-center border"
                  >
                    + Agregar Opción
                  </button>
                </div>
              </div>
            </div>

            <div v-if="showDateConfig" class="sm:col-span-3 col-span-6">
              <label for="date_max" class="text-sm font-medium text-gray-700 block">
                Fecha máxima
              </label>
              <input
                type="date"
                name="date_max"
                id="date_max"
                :class="['mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full', errors.date_max ? 'border-red-300' : '']"
                v-model="formData.date_max"
                @input="handleChange"
              />
              <p v-if="errors.date_max" class="mt-1 text-sm text-red-600">{{ errors.date_max }}</p>
            </div>

            <template v-if="showNumberConfig">
              <div class="sm:col-span-2 col-span-6">
                <label for="number_min" class="text-sm font-medium text-gray-700 block">
                  Valor mínimo
                </label>
                <input
                  type="number"
                  step="any"
                  name="number_min"
                  id="number_min"
                  :class="['mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full', errors.number_min ? 'border-red-300' : '']"
                  v-model="formData.number_min"
                  @input="handleChange"
                />
                <p v-if="errors.number_min" class="mt-1 text-sm text-red-600">{{ errors.number_min }}</p>
              </div>
              <div class="sm:col-span-2 col-span-6">
                <label for="number_max" class="text-sm font-medium text-gray-700 block">
                  Valor máximo
                </label>
                <input
                  type="number"
                  step="any"
                  name="number_max"
                  id="number_max"
                  :class="['mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full', errors.number_max ? 'border-red-300' : '']"
                  v-model="formData.number_max"
                  @input="handleChange"
                />
                <p v-if="errors.number_max" class="mt-1 text-sm text-red-600">{{ errors.number_max }}</p>
              </div>
              <div class="sm:col-span-2 col-span-6">
                <label for="number_step" class="text-sm font-medium text-gray-700 block">
                  Incremento *
                </label>
                <input
                  type="number"
                  step="any"
                  name="number_step"
                  id="number_step"
                  required
                  min="0.01"
                  :class="['mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white text-gray-900 p-2 block w-full', errors.number_step ? 'border-red-300' : '']"
                  v-model.number="formData.number_step"
                  @input="handleChange"
                />
                <p v-if="errors.number_step" class="mt-1 text-sm text-red-600">{{ errors.number_step }}</p>
              </div>
            </template>
          </div>

          <div class="pt-6 border-t border-gray-200 mt-6 flex justify-end">
            <button
              type="submit"
              :disabled="processing"
              class="px-4 py-2 text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:ring-indigo-500 inline-flex items-center border border-transparent focus:ring-2 focus:ring-offset-2 focus:outline-none disabled:opacity-50"
            >
              {{ processing ? 'Actualizando...' : 'Actualizar Componente' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </AppLayout>
</template>

// resources/js/pages/Mercurio/ComponenteDinamico/Edit.tsx
import AppLayout from '@/layouts/app-layout';
import { Link, router } from '@inertiajs/react';
import { useState, useEffect } from 'react';

type Props = {
    componente: {
        id: number;
        name: string;
        type: string;
        label: string;
        placeholder: string | null;
        form_type: string;
        group_id: number;
        order: number;
        default_value: string | null;
        is_disabled: boolean;
        is_readonly: boolean;
        data_source: any[] | null;
        css_classes: string | null;
        help_text: string | null;
        target: number;
        event_config: any;
        search_type: string | null;
        date_max: string | null;
        number_min: number | null;
        number_max: number | null;
        number_step: number;
    };
};

export default function Edit({ componente }: Props) {
    const [formData, setFormData] = useState({
        name: '',
        type: 'input',
        label: '',
        placeholder: '',
        form_type: 'input',
        group_id: 1,
        order: 1,
        default_value: '',
        is_disabled: false,
        is_readonly: false,
        data_source: [] as Array<{value: string, label: string}>,
        css_classes: '',
        help_text: '',
        target: -1,
        event_config: {} as any,
        search_type: '',
        date_max: '',
        number_min: '',
        number_max: '',
        number_step: 1,
    });

    const [errors, setErrors] = useState<Record<string, string>>({});
    const [processing, setProcessing] = useState(false);

    // Cargar datos del componente al montar el componente
    useEffect(() => {
        setFormData({
            name: componente.name || '',
            type: componente.type || 'input',
            label: componente.label || '',
            placeholder: componente.placeholder || '',
            form_type: componente.form_type || 'input',
            group_id: componente.group_id || 1,
            order: componente.order || 1,
            default_value: componente.default_value || '',
            is_disabled: componente.is_disabled || false,
            is_readonly: componente.is_readonly || false,
            data_source: componente.data_source || [],
            css_classes: componente.css_classes || '',
            help_text: componente.help_text || '',
            target: componente.target || -1,
            event_config: componente.event_config || {},
            search_type: componente.search_type || '',
            date_max: componente.date_max || '',
            number_min: componente.number_min?.toString() || '',
            number_max: componente.number_max?.toString() || '',
            number_step: componente.number_step || 1,
        });
    }, [componente]);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        const { name, value, type } = e.target;
        const checked = (e.target as HTMLInputElement).checked;

        setFormData(prev => ({
            ...prev,
            [name]: type === 'checkbox' ? checked : type === 'number' ? Number(value) : value
        }));

        // Limpiar error cuando el usuario comienza a escribir
        if (errors[name]) {
            setErrors(prev => ({
                ...prev,
                [name]: ''
            }));
        }
    };

    const handleDataSourceChange = (index: number, field: 'value' | 'label', value: string) => {
        setFormData(prev => ({
            ...prev,
            data_source: prev.data_source.map((item, i) =>
                i === index ? { ...item, [field]: value } : item
            )
        }));
    };

    const addDataSourceItem = () => {
        setFormData(prev => ({
            ...prev,
            data_source: [...prev.data_source, { value: '', label: '' }]
        }));
    };

    const removeDataSourceItem = (index: number) => {
        setFormData(prev => ({
            ...prev,
            data_source: prev.data_source.filter((_, i) => i !== index)
        }));
    };

    const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        setProcessing(true);

        try {
            const submitData = {
                ...formData,
                data_source: formData.type === 'select' ? formData.data_source : null,
                event_config: Object.keys(formData.event_config).length > 0 ? formData.event_config : null,
                date_max: formData.type === 'date' && formData.date_max ? formData.date_max : null,
                number_min: formData.type === 'number' && formData.number_min ? Number(formData.number_min) : null,
                number_max: formData.type === 'number' && formData.number_max ? Number(formData.number_max) : null,
                number_step: formData.type === 'number' ? Number(formData.number_step) : 1,
            };

            const response = await fetch(`/mercurio/componente-dinamico/${componente.id}`, {
                method: 'PUT',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.getAttribute('content') || ''
                },
                body: JSON.stringify(submitData)
            });

            const data = await response.json();

            if (response.ok) {
                router.visit('/mercurio/componente-dinamico');
            } else {
                if (data.errors) {
                    setErrors(data.errors);
                } else {
                    console.error('Error desconocido:', data);
                }
            }
        } catch (error) {
            console.error('Error al actualizar componente:', error);
        } finally {
            setProcessing(false);
        }
    };

    return (
        <AppLayout title={`Editar Componente: ${componente.label}`}>
            <div className="bg-white shadow overflow-hidden sm:rounded-md">
                <div className="px-4 py-5 sm:px-6 flex justify-between items-center">
                    <div>
                        <h3 className="text-lg leading-6 font-medium text-gray-900">
                            Editar Componente Dinámico
                        </h3>
                        <p className="mt-1 max-w-2xl text-sm text-gray-500">
                            Modificar los datos del componente dinámico
                        </p>
                    </div>
                    <Link
                        href="/mercurio/componente-dinamico"
                        className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700"
                    >
                        Volver
                    </Link>
                </div>
                <div className="px-4 py-5 sm:px-6">
                    <form onSubmit={handleSubmit}>
                        <div className="grid grid-cols-6 gap-6">
                            {/* Nombre único */}
                            <div className="col-span-6 sm:col-span-3">
                                <label htmlFor="name" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Nombre único *</label>
                                <input
                                    type="text"
                                    name="name"
                                    id="name"
                                    required
                                    className={`mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2 ${errors.name ? 'border-red-300' : ''}`}
                                    value={formData.name}
                                    onChange={handleChange}
                                />
                                {errors.name && (<p className="mt-1 text-sm text-red-600">{errors.name}</p>)}
                                <p className="mt-1 text-xs text-gray-500">Identificador único para el componente</p>
                            </div>

                            {/* Tipo */}
                            <div className="col-span-6 sm:col-span-3">
                                <label htmlFor="type" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Tipo *</label>
                                <select
                                    name="type"
                                    id="type"
                                    required
                                    className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2"
                                    value={formData.type}
                                    onChange={handleChange}
                                >
                                    <option value="input">Input (Texto)</option>
                                    <option value="select">Select (Lista desplegable)</option>
                                    <option value="textarea">Textarea (Texto largo)</option>
                                    <option value="date">Date (Fecha)</option>
                                    <option value="number">Number (Número)</option>
                                    <option value="dialog">Dialog (Modal)</option>
                                </select>
                                <p className="mt-1 text-xs text-gray-500">Tipo de componente</p>
                            </div>

                            {/* Etiqueta */}
                            <div className="col-span-6 sm:col-span-3">
                                <label htmlFor="label" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Etiqueta *</label>
                                <input
                                    type="text"
                                    name="label"
                                    id="label"
                                    required
                                    className={`mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2 ${errors.label ? 'border-red-300' : ''}`}
                                    value={formData.label}
                                    onChange={handleChange}
                                />
                                {errors.label && (<p className="mt-1 text-sm text-red-600">{errors.label}</p>)}
                                <p className="mt-1 text-xs text-gray-500">Texto visible del campo</p>
                            </div>

                            {/* Placeholder */}
                            <div className="col-span-6 sm:col-span-3">
                                <label htmlFor="placeholder" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Placeholder</label>
                                <input
                                    type="text"
                                    name="placeholder"
                                    id="placeholder"
                                    className={`mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2 ${errors.placeholder ? 'border-red-300' : ''}`}
                                    value={formData.placeholder}
                                    onChange={handleChange}
                                />
                                <p className="mt-1 text-xs text-gray-500">Texto de ayuda dentro del campo</p>
                            </div>

                            {/* Grupo y Orden */}
                            <div className="col-span-6 sm:col-span-2">
                                <label htmlFor="group_id" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Grupo *</label>
                                <input
                                    type="number"
                                    name="group_id"
                                    id="group_id"
                                    required
                                    min="1"
                                    className={`mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2 ${errors.group_id ? 'border-red-300' : ''}`}
                                    value={formData.group_id}
                                    onChange={handleChange}
                                />
                                <p className="mt-1 text-xs text-gray-500">ID del grupo al que pertenece</p>
                            </div>

                            <div className="col-span-6 sm:col-span-2">
                                <label htmlFor="order" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Orden *</label>
                                <input
                                    type="number"
                                    name="order"
                                    id="order"
                                    required
                                    min="1"
                                    className={`mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2 ${errors.order ? 'border-red-300' : ''}`}
                                    value={formData.order}
                                    onChange={handleChange}
                                />
                                <p className="mt-1 text-xs text-gray-500">Orden de aparición en el formulario</p>
                            </div>

                            {/* Estados */}
                            <div className="col-span-6 sm:col-span-2">
                                <div className="space-y-3">
                                    <div>
                                        <label className="inline-flex items-center">
                                            <input
                                                type="checkbox"
                                                name="is_disabled"
                                                id="is_disabled"
                                                className="rounded border-gray-300 text-indigo-600 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                                checked={formData.is_disabled}
                                                onChange={handleChange}
                                            />
                                            <span className="ml-2 text-sm text-gray-700">Deshabilitado</span>
                                        </label>
                                    </div>
                                    <div>
                                        <label className="inline-flex items-center">
                                            <input
                                                type="checkbox"
                                                name="is_readonly"
                                                id="is_readonly"
                                                className="rounded border-gray-300 text-indigo-600 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                                checked={formData.is_readonly}
                                                onChange={handleChange}
                                            />
                                            <span className="ml-2 text-sm text-gray-700">Solo lectura</span>
                                        </label>
                                    </div>
                                </div>
                            </div>

                            {/* Valor por defecto */}
                            <div className="col-span-6 sm:col-span-3">
                                <label htmlFor="default_value" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Valor por defecto</label>
                                <input
                                    type="text"
                                    name="default_value"
                                    id="default_value"
                                    className={`mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2 ${errors.default_value ? 'border-red-300' : ''}`}
                                    value={formData.default_value}
                                    onChange={handleChange}
                                />
                            </div>

                            {/* Texto de ayuda */}
                            <div className="col-span-6">
                                <label htmlFor="help_text" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Texto de ayuda</label>
                                <textarea
                                    name="help_text"
                                    id="help_text"
                                    rows={2}
                                    className={`mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2 ${errors.help_text ? 'border-red-300' : ''}`}
                                    value={formData.help_text}
                                    onChange={handleChange}
                                />
                            </div>

                            {/* Data Source para Select */}
                            {formData.type === 'select' && (
                                <div className="col-span-6">
                                    <div className="border-t border-gray-200 pt-6">
                                        <h4 className="text-sm font-medium text-gray-900 mb-4">Opciones del Select</h4>
                                        <div className="space-y-3">
                                            {formData.data_source.map((item, index) => (
                                                <div key={index} className="flex gap-3 items-end">
                                                    <div className="flex-1">
                                                        <label className="block text-sm font-medium text-gray-700">Valor</label>
                                                        <input
                                                            type="text"
                                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2"
                                                            value={item.value}
                                                            onChange={(e) => handleDataSourceChange(index, 'value', e.target.value)}
                                                            placeholder="Valor interno"
                                                        />
                                                    </div>
                                                    <div className="flex-1">
                                                        <label className="block text-sm font-medium text-gray-700">Etiqueta</label>
                                                        <input
                                                            type="text"
                                                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2"
                                                            value={item.label}
                                                            onChange={(e) => handleDataSourceChange(index, 'label', e.target.value)}
                                                            placeholder="Texto visible"
                                                        />
                                                    </div>
                                                    <button
                                                        type="button"
                                                        onClick={() => removeDataSourceItem(index)}
                                                        className="inline-flex items-center h-9 px-3 rounded-md border border-red-300 text-sm font-medium text-red-700 hover:bg-red-50"
                                                    >
                                                        ✕
                                                    </button>
                                                </div>
                                            ))}
                                            <button
                                                type="button"
                                                onClick={addDataSourceItem}
                                                className="inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm leading-4 font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50"
                                            >
                                                + Agregar Opción
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            )}

                            {/* Configuración específica por tipo */}
                            {formData.type === 'date' && (
                                <div className="col-span-6 sm:col-span-3">
                                    <label htmlFor="date_max" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Fecha máxima</label>
                                    <input
                                        type="date"
                                        name="date_max"
                                        id="date_max"
                                        className={`mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2 ${errors.date_max ? 'border-red-300' : ''}`}
                                        value={formData.date_max}
                                        onChange={handleChange}
                                    />
                                </div>
                            )}

                            {formData.type === 'number' && (
                                <>
                                    <div className="col-span-6 sm:col-span-2">
                                        <label htmlFor="number_min" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Valor mínimo</label>
                                        <input
                                            type="number"
                                            step="any"
                                            name="number_min"
                                            id="number_min"
                                            className={`mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2 ${errors.number_min ? 'border-red-300' : ''}`}
                                            value={formData.number_min}
                                            onChange={handleChange}
                                        />
                                    </div>
                                    <div className="col-span-6 sm:col-span-2">
                                        <label htmlFor="number_max" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Valor máximo</label>
                                        <input
                                            type="number"
                                            step="any"
                                            name="number_max"
                                            id="number_max"
                                            className={`mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2 ${errors.number_max ? 'border-red-300' : ''}`}
                                            value={formData.number_max}
                                            onChange={handleChange}
                                        />
                                    </div>
                                    <div className="col-span-6 sm:col-span-2">
                                        <label htmlFor="number_step" className="block text-sm font-medium text-gray-700 dark:text-gray-300">Incremento *</label>
                                        <input
                                            type="number"
                                            step="any"
                                            name="number_step"
                                            id="number_step"
                                            required
                                            min="0.01"
                                            className={`mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 p-2 ${errors.number_step ? 'border-red-300' : ''}`}
                                            value={formData.number_step}
                                            onChange={handleChange}
                                        />
                                    </div>
                                </>
                            )}
                        </div>

                        <div className="flex justify-end pt-6 border-t border-gray-200 mt-6">
                            <button
                                type="submit"
                                disabled={processing}
                                className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                                {processing ? 'Actualizando...' : 'Actualizar Componente'}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </AppLayout>
    );
}
