// resources/js/layouts/AppLayoutTemplate.vue
<script setup lang="ts">
import AppLayoutTemplate from '@/layouts/app/AppSidebarLayout.vue'
import type { BreadcrumbItem } from '@/types'

defineProps<{
  title: string
  breadcrumbs?: BreadcrumbItem[]
}>()
</script>

<template>
  <AppLayoutTemplate :breadcrumbs="$props.breadcrumbs">
    <slot />
  </AppLayoutTemplate>
</template>

// resources/js/layouts/AppLayoutTemplate.tsx
import AppLayoutTemplate from '@/layouts/app/AppSidebarLayout';
import { type BreadcrumbItem } from '@/types';
import { type ReactNode } from 'react';

interface AppLayoutProps {
    title: string;
    children: ReactNode;
    breadcrumbs?: BreadcrumbItem[];
}

export default ({ children, breadcrumbs, ...props }: AppLayoutProps) => (
    <AppLayoutTemplate breadcrumbs={breadcrumbs} {...props}>
        {children}
    </AppLayoutTemplate>
);
