// resources/js/pages/Auth/Register.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Link, router } from '@inertiajs/vue3'
import { route } from 'ziggy-js'
import { ChevronLeft } from 'lucide-vue-next'
import AppLogoIcon from '@/components/AppLogoIcon.vue'
import { Input } from '@/components/ui/input'
import { SelectRadix } from '@/components/ui/select'
import { useRegisterController } from '@/composables/useRegisterController'
import { userTypes } from '@/constants/auth'

const props = defineProps<{
    Coddoc?: Record<string, string>
    Tipsoc?: Record<string, string>
    Codciu?: Record<string, string>
    errors?: Record<string, string>
}>()

const {
    state,
    step,
    dialog,
    setDialog,
    documentTypeOptions,
    cityOptions,
    societyOptions,
    companyCategoryOptions,
    events,
    validateStep
} = useRegisterController(props.Coddoc || {}, props.Tipsoc || {}, props.Codciu || {}, props.errors || {})

const isCompany = computed(() => state.selectedUserType === 'empresa')
const isWorker = computed(() => state.selectedUserType === 'trabajador')
const isNatural = computed(() => state.companyCategory === 'N')
const maxSteps = computed(() => {
    if (isCompany.value) return state.userRole === 'delegado' ? 5 : 4
    if (isWorker.value) return 3
    return 2
})

function handleUserTypeSelect(id: string) {
    if (id === 'empresa') {
        router.visit(route('register.company'))
        return
    }
    if (id === 'trabajador') {
        router.visit(route('register.worker'))
        return
    }
    events.handleUserTypeSelect(id as any)
}

function handleFieldChange(field: string, value: any) {
    ;(state as any)[field] = value
}
</script>

<template>
  <div class="min-h-dvh w-full bg-white">
    <div class="flex min-h-dvh flex-col lg:flex-row lg:relative">
      <!-- Left Panel - Welcome Section (Desktop only) -->
      <div class="hidden lg:block lg:w-1/2 lg:min-h-dvh lg:relative lg:overflow-hidden">
        <!-- Absolute background layer -->
        <div class="absolute inset-0 bg-gradient-to-br from-emerald-600 via-emerald-700 to-teal-700" />

        <!-- Absolute decorative shapes -->
        <div class="absolute top-0 right-0 w-40 h-40 bg-gradient-to-br from-emerald-400 to-teal-500 rounded-full opacity-60 -translate-y-1/2 translate-x-1/4 pointer-events-none" />
        <div class="absolute bottom-0 left-0 w-32 h-32 bg-gradient-to-tr from-emerald-800 to-emerald-600 rounded-full opacity-40 -translate-y-1/3 -translate-x-1/4 pointer-events-none" />
        <div class="absolute top-1/2 left-0 w-20 h-20 bg-gradient-to-r from-teal-500 to-emerald-500 rounded-full opacity-30 -translate-y-1/2 -translate-x-1/2 pointer-events-none" />

        <!-- Content layer -->
        <div class="relative z-10 flex flex-col justify-center h-full p-5 text-white max-w-md mx-auto items-center">
          <Link :href="route('login')" class="flex items-center justify-center text-lg font-medium mb-2">
            <AppLogoIcon class="size-100 fill-current text-white" />
          </Link>

          <h1 class="text-4xl font-bold mb-2">REGISTRO</h1>
          <div class="w-16 h-0.5 bg-white mb-6" />
          <p class="text-emerald-100 text-lg mb-6">Únete a Comfaca En Línea</p>

          <div class="text-emerald-100 text-sm leading-relaxed mb-6 space-y-3">
            <p>Cree su cuenta y acceda a COMFACA de forma segura y eficiente para la gestión de sus trámites y servicios.</p>
          </div>

          <Link
            :href="route('login')"
            class="inline-flex items-center text-emerald-200 hover:text-white transition-colors text-sm mb-4"
          >
            <ChevronLeft class="w-4 h-4 mr-1" />
            ¿Ya tienes cuenta? Inicia sesión
          </Link>
        </div>
      </div>

      <!-- Right Panel - Register Form -->
      <div class="flex flex-1 flex-col justify-center px-6 py-10 lg:w-1/2 lg:px-16">
        <div class="w-full max-w-md mx-auto">
          <!-- Mobile Header -->
          <div class="flex lg:hidden items-center gap-3 mb-8">
            <img src="/img/comfaca-logo.png" alt="COMFACA" class="h-10 w-auto" />
            <span class="text-lg font-bold text-gray-900">COMFACA EN LÍNEA</span>
          </div>

          <!-- User Type Selection -->
          <div v-if="!state.selectedUserType" class="flex flex-col">
            <h1 class="text-2xl font-semibold text-gray-900 mb-1">Crear cuenta</h1>
            <p class="text-sm text-gray-500 mb-6">Selecciona tu tipo de usuario</p>

            <div class="grid grid-cols-2 gap-3 mb-6">
              <button
                v-for="ut in userTypes"
                :key="ut.id"
                type="button"
                class="flex flex-col items-center p-4 rounded-lg border border-gray-200 hover:border-emerald-500 hover:bg-emerald-50 transition-colors text-center"
                @click="handleUserTypeSelect(ut.id)"
              >
                <component :is="ut.icon" class="mb-2 w-6 h-6 text-gray-600" />
                <span class="text-xs font-medium text-gray-700">{{ ut.label }}</span>
              </button>
            </div>
          </div>

          <!-- Register Form -->
          <form v-else @submit="(e) => { e.preventDefault(); events.handleRegister(e) }" class="space-y-4">
            <div class="flex items-center justify-between mb-4">
              <button
                type="button"
                @click="events.handleBack"
                class="flex items-center text-sm text-gray-500 hover:text-emerald-600 transition-colors"
              >
                <ChevronLeft class="w-4 h-4 mr-1" />
                Volver
              </button>
              <span class="text-sm text-gray-500">Paso {{ step }} de {{ maxSteps }}</span>
            </div>

            <div v-if="step === 1 && isCompany" class="space-y-4">
              <h3 class="text-lg font-medium">Datos de la empresa</h3>

              <div>
                <label class="block text-sm font-medium text-gray-700">Nombre de la empresa *</label>
                <Input
                  :modelValue="state.companyName"
                  @update:modelValue="(v) => handleFieldChange('companyName', String(v))"
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.companyName" class="mt-1 text-sm text-red-600">{{ state.errors.companyName }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">NIT *</label>
                <Input
                  :modelValue="state.companyNit"
                  @update:modelValue="(v) => handleFieldChange('companyNit', String(v))"
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.companyNit" class="mt-1 text-sm text-red-600">{{ state.errors.companyNit }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Tipo de documento</label>
                <SelectRadix
                  :modelValue="state.companyDocumentType"
                  @update:modelValue="(v) => handleFieldChange('companyDocumentType', String(v))"
                  :options="documentTypeOptions"
                  placeholder="Seleccione..."
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.companyDocumentType" class="mt-1 text-sm text-red-600">{{ state.errors.companyDocumentType }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">No. Documento *</label>
                <Input
                  :modelValue="state.companyDocument"
                  @update:modelValue="(v) => handleFieldChange('companyDocument', String(v))"
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.companyDocument" class="mt-1 text-sm text-red-600">{{ state.errors.companyDocument }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Ciudad</label>
                <SelectRadix
                  :modelValue="state.companyCity"
                  @update:modelValue="(v) => handleFieldChange('companyCity', String(v))"
                  :options="cityOptions"
                  placeholder="Seleccione..."
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.companyCity" class="mt-1 text-sm text-red-600">{{ state.errors.companyCity }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Dirección</label>
                <Input
                  :modelValue="state.companyAddress"
                  @update:modelValue="(v) => handleFieldChange('companyAddress', String(v))"
                  class="mt-1 w-full"
                />
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Teléfono</label>
                <Input
                  :modelValue="state.companyPhone"
                  @update:modelValue="(v) => handleFieldChange('companyPhone', String(v))"
                  class="mt-1 w-full"
                />
              </div>
            </div>

            <div v-if="step === 1 && isWorker" class="space-y-4">
              <h3 class="text-lg font-medium">Datos del trabajador</h3>

              <div>
                <label class="block text-sm font-medium text-gray-700">Tipo de documento *</label>
                <SelectRadix
                  :modelValue="state.documentType"
                  @update:modelValue="(v) => handleFieldChange('documentType', String(v))"
                  :options="documentTypeOptions"
                  placeholder="Seleccione..."
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.documentType" class="mt-1 text-sm text-red-600">{{ state.errors.documentType }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">No. Documento *</label>
                <Input
                  :modelValue="state.documentNumber"
                  @update:modelValue="(v) => handleFieldChange('documentNumber', String(v))"
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.documentNumber" class="mt-1 text-sm text-red-600">{{ state.errors.documentNumber }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Primer nombre *</label>
                <Input
                  :modelValue="state.firstName"
                  @update:modelValue="(v) => handleFieldChange('firstName', String(v))"
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.firstName" class="mt-1 text-sm text-red-600">{{ state.errors.firstName }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Segundo nombre</label>
                <Input
                  :modelValue="state.secondName"
                  @update:modelValue="(v) => handleFieldChange('secondName', String(v))"
                  class="mt-1 w-full"
                />
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Primer apellido *</label>
                <input
                  type="text"
                  class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500 sm:text-sm p-2"
                  :value="state.lastName"
                  @input="handleFieldChange('lastName', ($event.target as HTMLInputElement).value)"
                />
                <p v-if="state.errors.lastName" class="mt-1 text-sm text-red-600">{{ state.errors.lastName }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Segundo apellido</label>
                <input
                  type="text"
                  class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500 sm:text-sm p-2"
                  :value="state.secondLastName"
                  @input="handleFieldChange('secondLastName', ($event.target as HTMLInputElement).value)"
                />
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Ciudad</label>
                <SelectRadix
                  :modelValue="state.city"
                  @update:modelValue="(v) => handleFieldChange('city', String(v))"
                  :options="cityOptions"
                  placeholder="Seleccione..."
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.city" class="mt-1 text-sm text-red-600">{{ state.errors.city }}</p>
              </div>
            </div>

            <div v-if="step === 1 && !isCompany && !isWorker" class="space-y-4">
              <h3 class="text-lg font-medium">Datos personales</h3>

              <div>
                <label class="block text-sm font-medium text-gray-700">Tipo de documento *</label>
                <SelectRadix
                  :modelValue="state.documentType"
                  @update:modelValue="(v) => handleFieldChange('documentType', String(v))"
                  :options="documentTypeOptions"
                  placeholder="Seleccione..."
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.documentType" class="mt-1 text-sm text-red-600">{{ state.errors.documentType }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">No. Documento *</label>
                <Input
                  :modelValue="state.documentNumber"
                  @update:modelValue="(v) => handleFieldChange('documentNumber', String(v))"
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.documentNumber" class="mt-1 text-sm text-red-600">{{ state.errors.documentNumber }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Primer nombre *</label>
                <Input
                  :modelValue="state.firstName"
                  @update:modelValue="(v) => handleFieldChange('firstName', String(v))"
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.firstName" class="mt-1 text-sm text-red-600">{{ state.errors.firstName }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Segundo nombre</label>
                <Input
                  :modelValue="state.secondName"
                  @update:modelValue="(v) => handleFieldChange('secondName', String(v))"
                  class="mt-1 w-full"
                />
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Primer apellido *</label>
                <Input
                  :modelValue="state.lastName"
                  @update:modelValue="(v) => handleFieldChange('lastName', String(v))"
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.lastName" class="mt-1 text-sm text-red-600">{{ state.errors.lastName }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Segundo apellido</label>
                <Input
                  :modelValue="state.secondLastName"
                  @update:modelValue="(v) => handleFieldChange('secondLastName', String(v))"
                  class="mt-1 w-full"
                />
              </div>
            </div>

            <div v-if="step === 2 && isCompany" class="space-y-4">
              <h3 class="text-lg font-medium">Categoría de la empresa</h3>

              <div>
                <label class="block text-sm font-medium text-gray-700">Categoría</label>
                <SelectRadix
                  :modelValue="state.companyCategory"
                  @update:modelValue="(v) => handleFieldChange('companyCategory', String(v))"
                  :options="companyCategoryOptions"
                  placeholder="Seleccione..."
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.companyCategory" class="mt-1 text-sm text-red-600">{{ state.errors.companyCategory }}</p>
              </div>

              <div v-if="!isNatural">
                <label class="block text-sm font-medium text-gray-700">Tipo de empresa</label>
                <SelectRadix
                  :modelValue="state.companyType"
                  @update:modelValue="(v) => handleFieldChange('companyType', String(v))"
                  :options="societyOptions"
                  placeholder="Seleccione..."
                  class="mt-1 w-full"
                />
              </div>

              <div v-if="!isNatural">
                <label class="block text-sm font-medium text-gray-700">NIT de la empresa principal (si aplica)</label>
                <Input
                  :modelValue="state.mainCompanyNit"
                  @update:modelValue="(v) => handleFieldChange('mainCompanyNit', String(v))"
                  class="mt-1 w-full"
                />
              </div>
            </div>

            <div v-if="step === 2 && isWorker" class="space-y-4">
              <h3 class="text-lg font-medium">Datos del afiliado</h3>

              <div>
                <label class="block text-sm font-medium text-gray-700">Empresa donde labora *</label>
                <Input
                  :modelValue="state.companyName"
                  @update:modelValue="(v) => handleFieldChange('companyName', String(v))"
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.companyName" class="mt-1 text-sm text-red-600">{{ state.errors.companyName }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">NIT de la empresa *</label>
                <Input
                  :modelValue="state.companyNit"
                  @update:modelValue="(v) => handleFieldChange('companyNit', String(v))"
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.companyNit" class="mt-1 text-sm text-red-600">{{ state.errors.companyNit }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Ciudad</label>
                <SelectRadix
                  :modelValue="state.city"
                  @update:modelValue="(v) => handleFieldChange('city', String(v))"
                  :options="cityOptions"
                  placeholder="Seleccione..."
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.city" class="mt-1 text-sm text-red-600">{{ state.errors.city }}</p>
              </div>
            </div>

            <div v-if="step === 2 && !isCompany && !isWorker" class="space-y-4">
              <h3 class="text-lg font-medium">Información adicional</h3>

              <div>
                <label class="block text-sm font-medium text-gray-700">Ciudad</label>
                <SelectRadix
                  :modelValue="state.city"
                  @update:modelValue="(v) => handleFieldChange('city', String(v))"
                  :options="cityOptions"
                  placeholder="Seleccione..."
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.city" class="mt-1 text-sm text-red-600">{{ state.errors.city }}</p>
              </div>
            </div>

            <div v-if="step === 3 && isWorker" class="space-y-4">
              <h3 class="text-lg font-medium">Datos del beneficiario</h3>

              <div>
                <label class="block text-sm font-medium text-gray-700">¿Es usted mismo el beneficiario? *</label>
                <SelectRadix
                  :modelValue="state.isSelfBeneficiary"
                  @update:modelValue="(v) => handleFieldChange('isSelfBeneficiary', String(v))"
                  :options="[{ value: 'si', label: 'Sí' }, { value: 'no', label: 'No' }]"
                  placeholder="Seleccione..."
                  class="mt-1 w-full"
                />
              </div>
            </div>

            <div v-if="(step === 3 && !isCompany && !isWorker) || (step === 4 && isCompany) || (step === 3 && isWorker)" class="space-y-4">
              <h3 class="text-lg font-medium">Datos de contacto</h3>

              <div>
                <label class="block text-sm font-medium text-gray-700">Correo electrónico *</label>
                <input
                  type="email"
                  class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500 sm:text-sm p-2"
                  :value="state.email"
                  @input="handleFieldChange('email', ($event.target as HTMLInputElement).value)"
                />
                <p v-if="state.errors.email" class="mt-1 text-sm text-red-600">{{ state.errors.email }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Confirmar correo electrónico *</label>
                <input
                  type="email"
                  class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500 sm:text-sm p-2"
                  :value="state.confirmEmail"
                  @input="handleFieldChange('confirmEmail', ($event.target as HTMLInputElement).value)"
                />
                <p v-if="state.errors.confirmEmail" class="mt-1 text-sm text-red-600">{{ state.errors.confirmEmail }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Celular</label>
                <Input
                  :modelValue="state.cellphone"
                  @update:modelValue="(v) => handleFieldChange('cellphone', String(v))"
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.cellphone" class="mt-1 text-sm text-red-600">{{ state.errors.cellphone }}</p>
              </div>
            </div>

            <div v-if="step === 4 && isCompany && state.userRole !== 'delegado'" class="space-y-4">
              <h3 class="text-lg font-medium">Datos del usuario</h3>

              <div>
                <label class="block text-sm font-medium text-gray-700">Nombres completos *</label>
                <Input
                  :modelValue="state.firstName"
                  @update:modelValue="(v) => handleFieldChange('firstName', String(v))"
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.firstName" class="mt-1 text-sm text-red-600">{{ state.errors.firstName }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Apellidos completos *</label>
                <Input
                  :modelValue="state.lastName"
                  @update:modelValue="(v) => handleFieldChange('lastName', String(v))"
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.lastName" class="mt-1 text-sm text-red-600">{{ state.errors.lastName }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Tipo de documento *</label>
                <SelectRadix
                  :modelValue="state.documentType"
                  @update:modelValue="(v) => handleFieldChange('documentType', String(v))"
                  :options="documentTypeOptions"
                  placeholder="Seleccione..."
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.documentType" class="mt-1 text-sm text-red-600">{{ state.errors.documentType }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">No. Documento *</label>
                <Input
                  :modelValue="state.documentNumber"
                  @update:modelValue="(v) => handleFieldChange('documentNumber', String(v))"
                  class="mt-1 w-full"
                />
                <p v-if="state.errors.documentNumber" class="mt-1 text-sm text-red-600">{{ state.errors.documentNumber }}</p>
              </div>
            </div>

            <div v-if="(step === 5 && isCompany && state.userRole === 'delegado') || (step === 4 && !isCompany && !isWorker) || (step === 4 && isWorker)" class="space-y-4">
              <h3 class="text-lg font-medium">Configuración de clave</h3>

              <div>
                <label class="block text-sm font-medium text-gray-700">Clave *</label>
                <input
                  type="password"
                  class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500 sm:text-sm p-2"
                  :value="state.password"
                  @input="handleFieldChange('password', ($event.target as HTMLInputElement).value)"
                />
                <p v-if="state.errors.password" class="mt-1 text-sm text-red-600">{{ state.errors.password }}</p>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700">Confirmar clave *</label>
                <input
                  type="password"
                  class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500 sm:text-sm p-2"
                  :value="state.confirmPassword"
                  @input="handleFieldChange('confirmPassword', ($event.target as HTMLInputElement).value)"
                />
                <p v-if="state.errors.confirmPassword" class="mt-1 text-sm text-red-600">{{ state.errors.confirmPassword }}</p>
              </div>
            </div>

            <div class="flex justify-between pt-4">
              <button
                v-if="step > 1"
                type="button"
                @click="events.handlePrevStep"
                class="px-4 py-2 text-sm font-medium rounded-md border border-gray-300 text-gray-700 bg-white hover:bg-gray-50"
              >
                Anterior
              </button>
              <button
                type="button"
                @click="events.handleNextStep"
                class="px-4 py-2 text-sm font-medium rounded-md text-white bg-emerald-600 hover:bg-emerald-700 ml-auto"
              >
                {{ step === maxSteps ? 'Registrarse' : 'Siguiente' }}
              </button>
            </div>
          </form>
        </div>
      </div>

      <!-- Dialog -->
      <div v-if="dialog" class="fixed inset-0 z-50 flex items-center justify-center">
        <div class="absolute inset-0 bg-black/40" @click="setDialog(null)" />
        <div class="relative bg-white rounded-lg shadow-xl w-full max-w-md mx-4 p-6">
          <div class="mb-4">
            <h3 :class="['text-lg font-medium', dialog.type === 'success' ? 'text-emerald-600' : 'text-red-600']">
              {{ dialog.type === 'success' ? 'Registro Exitoso' : 'Error en el Registro' }}
            </h3>
          </div>
          <div class="mb-4">
            <p class="text-sm text-gray-700 whitespace-pre-line">{{ dialog.message }}</p>
          </div>
          <div class="flex justify-end gap-2">
            <button
              @click="setDialog(null)"
              class="px-4 py-2 text-sm font-medium rounded-md border border-gray-300 text-gray-700 bg-white hover:bg-gray-50"
            >
              Cerrar
            </button>
            <button
              v-if="dialog.showLoginButton"
              @click="router.visit(route('login'))"
              class="px-4 py-2 text-sm font-medium rounded-md text-white bg-emerald-600 hover:bg-emerald-700"
            >
              Ir al Login
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// resources/js/pages/Auth/Register.tsx
import type React from "react"
import { useReducer, useRef, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Building2, GraduationCap, Briefcase, Users, Home, HardHat, ChevronLeft } from "lucide-react"
import imageLogo from "../../assets/comfaca-logo.png";
import AuthLayout from "@/layouts/auth-layout";
import TextLink from "@/components/text-link";

type UserType = "empresa" | "independiente" | "facultativo" | "particular" | "domestico" | "trabajador"

interface UserTypeOption {
  id: UserType
  label: string
  icon: React.ReactNode
}

const userTypes: UserTypeOption[] = [
  { id: "empresa", label: "Empresa aportante", icon: <Building2 className="w-8 h-8 text-blue-500" /> },
  { id: "independiente", label: "Independiente aportante", icon: <GraduationCap className="w-8 h-8 text-green-500" /> },
  { id: "facultativo", label: "Facultativo", icon: <Briefcase className="w-8 h-8 text-purple-500" /> },
  { id: "particular", label: "Particular", icon: <Users className="w-8 h-8 text-orange-500" /> },
  { id: "domestico", label: "Servicio doméstico", icon: <Home className="w-8 h-8 text-red-500" /> },
  { id: "trabajador", label: "Trabajador", icon: <HardHat className="w-8 h-8 text-yellow-500" /> },
]

const documentTypes = [
  { value: "cc", label: "Cédula de Ciudadanía" },
  { value: "ce", label: "Cédula de Extranjería" },
  { value: "nit", label: "NIT" },
  { value: "pasaporte", label: "Pasaporte" },
]

interface FormState {
  selectedUserType: UserType | null
  documentType: string
  identification: string
  firstName: string
  lastName: string
  email: string
  phone: string
  password: string
  confirmPassword: string
  companyName: string
  companyNit: string
  address: string
  errors: Record<string, string>
  isSubmitting: boolean
}

type FormAction =
  | { type: "SET_USER_TYPE"; payload: UserType }
  | { type: "SET_FIELD"; field: keyof FormState; value: string }
  | { type: "SET_ERROR"; field: string; error: string }
  | { type: "CLEAR_ERRORS" }
  | { type: "SET_SUBMITTING"; payload: boolean }
  | { type: "RESET_FORM" }

const initialState: FormState = {
  selectedUserType: null,
  documentType: "",
  identification: "",
  firstName: "",
  lastName: "",
  email: "",
  phone: "",
  password: "",
  confirmPassword: "",
  companyName: "",
  companyNit: "",
  address: "",
  errors: {},
  isSubmitting: false,
}

function formReducer(state: FormState, action: FormAction): FormState {
  switch (action.type) {
    case "SET_USER_TYPE":
      return { ...state, selectedUserType: action.payload }
    case "SET_FIELD":
      return {
        ...state,
        [action.field]: action.value,
        errors: { ...state.errors, [action.field]: "" },
      }
    case "SET_ERROR":
      return {
        ...state,
        errors: { ...state.errors, [action.field]: action.error },
      }
    case "CLEAR_ERRORS":
      return { ...state, errors: {} }
    case "SET_SUBMITTING":
      return { ...state, isSubmitting: action.payload }
    case "RESET_FORM":
      return initialState
    default:
      return state
  }
}

interface ReactProps {
  status?: string;
  canResetPassword: boolean;
}

export default function Register({ status, canResetPassword }: ReactProps){ 
  const [state, dispatch] = useReducer(formReducer, initialState)

  const firstNameRef = useRef<HTMLInputElement>(null)
  const lastNameRef = useRef<HTMLInputElement>(null)
  const emailRef = useRef<HTMLInputElement>(null)
  const phoneRef = useRef<HTMLInputElement>(null)
  const identificationRef = useRef<HTMLInputElement>(null)
  const passwordRef = useRef<HTMLInputElement>(null)
  const confirmPasswordRef = useRef<HTMLInputElement>(null)
  const companyNameRef = useRef<HTMLInputElement>(null)
  const companyNitRef = useRef<HTMLInputElement>(null)
  const addressRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    if (state.selectedUserType && firstNameRef.current) {
      firstNameRef.current.focus()
    }
  }, [state.selectedUserType])

  const handleUserTypeSelect = (userType: UserType) => {
    dispatch({ type: "SET_USER_TYPE", payload: userType })
  }

  const handleBack = () => {
    dispatch({ type: "RESET_FORM" })
  }

  const validateForm = (): boolean => {
    dispatch({ type: "CLEAR_ERRORS" })
    let isValid = true

    // Document type validation
    if (!state.documentType) {
      dispatch({ type: "SET_ERROR", field: "documentType", error: "El tipo de documento es requerido" })
      isValid = false
    }

    // Basic field validation
    if (!state.firstName.trim()) {
      dispatch({ type: "SET_ERROR", field: "firstName", error: "El nombre es requerido" })
      firstNameRef.current?.focus()
      isValid = false
    }

    if (!state.lastName.trim()) {
      dispatch({ type: "SET_ERROR", field: "lastName", error: "El apellido es requerido" })
      if (isValid) lastNameRef.current?.focus()
      isValid = false
    }

    if (!state.email.trim()) {
      dispatch({ type: "SET_ERROR", field: "email", error: "El email es requerido" })
      if (isValid) emailRef.current?.focus()
      isValid = false
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(state.email)) {
      dispatch({ type: "SET_ERROR", field: "email", error: "Email inválido" })
      if (isValid) emailRef.current?.focus()
      isValid = false
    }

    if (!state.identification.trim()) {
      dispatch({ type: "SET_ERROR", field: "identification", error: "La identificación es requerida" })
      if (isValid) identificationRef.current?.focus()
      isValid = false
    }

    if (!state.password.trim()) {
      dispatch({ type: "SET_ERROR", field: "password", error: "La contraseña es requerida" })
      if (isValid) passwordRef.current?.focus()
      isValid = false
    } else if (state.password.length < 6) {
      dispatch({ type: "SET_ERROR", field: "password", error: "La contraseña debe tener al menos 6 caracteres" })
      if (isValid) passwordRef.current?.focus()
      isValid = false
    }

    if (state.password !== state.confirmPassword) {
      dispatch({ type: "SET_ERROR", field: "confirmPassword", error: "Las contraseñas no coinciden" })
      if (isValid) confirmPasswordRef.current?.focus()
      isValid = false
    }

    // Company-specific validation
    if (state.selectedUserType === "empresa") {
      if (!state.companyName.trim()) {
        dispatch({ type: "SET_ERROR", field: "companyName", error: "El nombre de la empresa es requerido" })
        if (isValid) companyNameRef.current?.focus()
        isValid = false
      }
      if (!state.companyNit.trim()) {
        dispatch({ type: "SET_ERROR", field: "companyNit", error: "El NIT de la empresa es requerido" })
        if (isValid) companyNitRef.current?.focus()
        isValid = false
      }
    }

    return isValid
  }

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!validateForm()) {
      return
    }

    dispatch({ type: "SET_SUBMITTING", payload: true })

    try {
      // Simulate API call
      await new Promise((resolve) => setTimeout(resolve, 2000))

      // Log registration data for development
      console.log("[v0] Registration data:", {
        userType: state.selectedUserType,
        personalInfo: {
          firstName: state.firstName,
          lastName: state.lastName,
          email: state.email,
          phone: state.phone,
        },
        document: {
          type: state.documentType,
          number: state.identification,
        },
        ...(state.selectedUserType === "empresa" && {
          company: {
            name: state.companyName,
            nit: state.companyNit,
          },
        }),
        address: state.address,
      })

      // Show success message and redirect
      alert("¡Registro exitoso! Serás redirigido al login.")

      // Reset form and redirect to login
      dispatch({ type: "RESET_FORM" })
      window.location.href = "/"
    } catch (error) {
      console.error("Registration error:", error)
      alert("Error en el registro. Por favor intenta nuevamente.")
    } finally {
      dispatch({ type: "SET_SUBMITTING", payload: false })
    }
  }

  const isCompanyType = state.selectedUserType === "empresa"

  return (
    <AuthLayout title="Log in to your account" description="Enter your email and password below to log in">
      {/* Left Panel - Welcome Section */}
      <div className="lg:w-1/2 bg-gradient-to-br from-emerald-600 via-emerald-700 to-teal-700 text-white p-12 flex flex-col justify-center relative overflow-hidden">
        <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-emerald-400 to-teal-500 rounded-full -translate-y-16 translate-x-16 opacity-60"></div>
        <div className="absolute bottom-0 left-0 w-24 h-24 bg-gradient-to-tr from-emerald-800 to-emerald-600 rounded-full translate-y-12 -translate-x-12 opacity-40"></div>
        <div className="absolute top-1/2 left-0 w-16 h-16 bg-gradient-to-r from-teal-500 to-emerald-500 rounded-full -translate-x-8 opacity-30"></div>

        <div className="relative z-10">
          <h1 className="text-4xl font-bold mb-2">REGISTRO</h1>
          <div className="w-16 h-0.5 bg-white mb-6"></div>
          <p className="text-emerald-100 text-lg mb-6">Únete a Value Aims</p>

          <p className="text-emerald-100 text-sm leading-relaxed mb-6">
            Crea tu cuenta para acceder a todos los servicios y beneficios que Value Aims tiene para ofrecerte. Un
            proceso simple y seguro para comenzar tu experiencia.
          </p>

          <TextLink href={route('login')}
            className="inline-flex items-center text-emerald-200 hover:text-white transition-colors text-sm"
          >
            <ChevronLeft className="w-4 h-4 mr-1" />
            ¿Ya tienes cuenta? Inicia sesión
          </TextLink>
        </div>
      </div>

      {/* Right Panel - Registration Form */}
      <div className="lg:w-1/2 p-8 flex flex-col justify-center relative overflow-y-auto max-h-[700px]">
        <div className="absolute top-6 right-6 w-16 h-16 bg-gradient-to-br from-emerald-200 to-teal-300 rounded-2xl opacity-70"></div>
        <div className="absolute bottom-6 right-12 w-8 h-8 bg-gradient-to-tr from-emerald-300 to-green-400 rounded-lg opacity-50"></div>
        <div className="absolute top-1/3 left-6 w-12 h-12 bg-gradient-to-bl from-teal-200 to-emerald-200 rounded-full opacity-40"></div>

        <div className="max-w-md mx-auto w-full">
          {!state.selectedUserType ? (
            <>
            <div className="mb-6 flex justify-center">
            <img
              src={imageLogo}
              alt="Comfaca Logo"
              width={180}
              height={60}
              className="opacity-90"
            />
          </div>
              <h2 className="text-2xl font-semibold text-gray-800 mb-2 text-center">Crear cuenta</h2>
              <p className="text-lg text-gray-600 mb-8 text-center">Selecciona tu tipo de usuario</p>

              <div className="grid grid-cols-3 gap-4 mb-8">
                {userTypes.map((userType) => (
                  <button
                    key={userType.id}
                    onClick={() => handleUserTypeSelect(userType.id)}
                    className="flex flex-col items-center p-4 rounded-lg border-2 border-gray-200 hover:border-emerald-500 hover:bg-gradient-to-br hover:from-emerald-50 hover:to-teal-50 transition-all duration-200 group"
                  >
                    <div className="text-emerald-600 group-hover:text-emerald-700 mb-2">{userType.icon}</div>
                    <span className="text-xs text-gray-600 text-center font-medium">{userType.label}</span>
                  </button>
                ))}
              </div>
            </>
          ) : (
            <>
              <div className="flex items-center mb-6">
                <button onClick={handleBack} className="mr-3 p-2 hover:bg-gray-100 rounded-full transition-colors">
                  <ChevronLeft className="w-5 h-5 text-gray-600" />
                </button>
                <div>
                  <h2 className="text-xl font-semibold text-gray-800">
                    {userTypes.find((ut) => ut.id === state.selectedUserType)?.label}
                  </h2>
                  <p className="text-sm text-gray-600">Completa tu información</p>
                </div>
              </div>

              <form onSubmit={handleRegister} className="space-y-4">
                {/* Personal Information */}
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="firstName" className="text-sm font-medium text-gray-700">
                      Nombre *
                    </Label>
                    <Input
                      id="firstName"
                      ref={firstNameRef}
                      type="text"
                      value={state.firstName}
                      onChange={(e) => dispatch({ type: "SET_FIELD", field: "firstName", value: e.target.value })}
                      placeholder="Tu nombre"
                      className={`mt-1 ${state.errors.firstName ? "border-red-500" : ""}`}
                    />
                    {state.errors.firstName && (
                      <p className="text-red-500 text-xs mt-1">{state.errors.firstName}</p>
                    )}
                  </div>

                  <div>
                    <Label htmlFor="lastName" className="text-sm font-medium text-gray-700">
                      Apellido *
                    </Label>
                    <Input
                      id="lastName"
                      ref={lastNameRef}
                      type="text"
                      value={state.lastName}
                      onChange={(e) => dispatch({ type: "SET_FIELD", field: "lastName", value: e.target.value })}
                      placeholder="Tu apellido"
                      className={`mt-1 ${state.errors.lastName ? "border-red-500" : ""}`}
                    />
                    {state.errors.lastName && <p className="text-red-500 text-xs mt-1">{state.errors.lastName}</p>}
                  </div>
                </div>

                <div>
                  <Label htmlFor="email" className="text-sm font-medium text-gray-700">
                    Email *
                  </Label>
                  <Input
                    id="email"
                    ref={emailRef}
                    type="email"
                    value={state.email}
                    onChange={(e) => dispatch({ type: "SET_FIELD", field: "email", value: e.target.value })}
                    placeholder="tu@email.com"
                    className={`mt-1 ${state.errors.email ? "border-red-500" : ""}`}
                  />
                  {state.errors.email && <p className="text-red-500 text-xs mt-1">{state.errors.email}</p>}
                </div>

                <div>
                  <Label htmlFor="phone" className="text-sm font-medium text-gray-700">
                    Teléfono
                  </Label>
                  <Input
                    id="phone"
                    ref={phoneRef}
                    type="tel"
                    value={state.phone}
                    onChange={(e) => dispatch({ type: "SET_FIELD", field: "phone", value: e.target.value })}
                    placeholder="Tu número de teléfono"
                    className="mt-1"
                  />
                </div>

                {/* Document Information */}
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="documentType" className="text-sm font-medium text-gray-700">
                      Tipo de documento *
                    </Label>
                    <Select
                      value={state.documentType}
                      onValueChange={(value) => dispatch({ type: "SET_FIELD", field: "documentType", value })}
                    >
                      <SelectTrigger className={`mt-1 ${state.errors.documentType ? "border-red-500" : ""}`}>
                        <SelectValue placeholder="Selecciona" />
                      </SelectTrigger>
                      <SelectContent>
                        {documentTypes.map((doc) => (
                          <SelectItem key={doc.value} value={doc.value}>
                            {doc.label}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    {state.errors.documentType && (
                      <p className="text-red-500 text-xs mt-1">{state.errors.documentType}</p>
                    )}
                  </div>

                  <div>
                    <Label htmlFor="identification" className="text-sm font-medium text-gray-700">
                      Número *
                    </Label>
                    <Input
                      id="identification"
                      ref={identificationRef}
                      type="text"
                      value={state.identification}
                      onChange={(e) =>
                        dispatch({ type: "SET_FIELD", field: "identification", value: e.target.value })
                      }
                      placeholder="Número de documento"
                      className={`mt-1 ${state.errors.identification ? "border-red-500" : ""}`}
                    />
                    {state.errors.identification && (
                      <p className="text-red-500 text-xs mt-1">{state.errors.identification}</p>
                    )}
                  </div>
                </div>

                {/* Company Information (only for empresa type) */}
                {isCompanyType && (
                  <>
                    <div>
                      <Label htmlFor="companyName" className="text-sm font-medium text-gray-700">
                        Nombre de la empresa *
                      </Label>
                      <Input
                        id="companyName"
                        ref={companyNameRef}
                        type="text"
                        value={state.companyName}
                        onChange={(e) =>
                          dispatch({ type: "SET_FIELD", field: "companyName", value: e.target.value })
                        }
                        placeholder="Nombre de tu empresa"
                        className={`mt-1 ${state.errors.companyName ? "border-red-500" : ""}`}
                      />
                      {state.errors.companyName && (
                        <p className="text-red-500 text-xs mt-1">{state.errors.companyName}</p>
                      )}
                    </div>

                    <div>
                      <Label htmlFor="companyNit" className="text-sm font-medium text-gray-700">
                        NIT de la empresa *
                      </Label>
                      <Input
                        id="companyNit"
                        ref={companyNitRef}
                        type="text"
                        value={state.companyNit}
                        onChange={(e) =>
                          dispatch({ type: "SET_FIELD", field: "companyNit", value: e.target.value })
                        }
                        placeholder="NIT de la empresa"
                        className={`mt-1 ${state.errors.companyNit ? "border-red-500" : ""}`}
                      />
                      {state.errors.companyNit && (
                        <p className="text-red-500 text-xs mt-1">{state.errors.companyNit}</p>
                      )}
                    </div>
                  </>
                )}

                <div>
                  <Label htmlFor="address" className="text-sm font-medium text-gray-700">
                    Dirección
                  </Label>
                  <Input
                    id="address"
                    ref={addressRef}
                    type="text"
                    value={state.address}
                    onChange={(e) => dispatch({ type: "SET_FIELD", field: "address", value: e.target.value })}
                    placeholder="Tu dirección"
                    className="mt-1"
                  />
                </div>

                {/* Password Fields */}
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="password" className="text-sm font-medium text-gray-700">
                      Contraseña *
                    </Label>
                    <Input
                      id="password"
                      ref={passwordRef}
                      type="password"
                      value={state.password}
                      onChange={(e) => dispatch({ type: "SET_FIELD", field: "password", value: e.target.value })}
                      placeholder="Mínimo 6 caracteres"
                      className={`mt-1 ${state.errors.password ? "border-red-500" : ""}`}
                    />
                    {state.errors.password && <p className="text-red-500 text-xs mt-1">{state.errors.password}</p>}
                  </div>

                  <div>
                    <Label htmlFor="confirmPassword" className="text-sm font-medium text-gray-700">
                      Confirmar *
                    </Label>
                    <Input
                      id="confirmPassword"
                      ref={confirmPasswordRef}
                      type="password"
                      value={state.confirmPassword}
                      onChange={(e) =>
                        dispatch({ type: "SET_FIELD", field: "confirmPassword", value: e.target.value })
                      }
                      placeholder="Repite la contraseña"
                      className={`mt-1 ${state.errors.confirmPassword ? "border-red-500" : ""}`}
                    />
                    {state.errors.confirmPassword && (
                      <p className="text-red-500 text-xs mt-1">{state.errors.confirmPassword}</p>
                    )}
                  </div>
                </div>

                <Button
                  type="submit"
                  disabled={state.isSubmitting}
                  className="w-full bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white py-3 rounded-lg font-medium shadow-lg mt-6"
                >
                  {state.isSubmitting ? "Registrando..." : "Crear cuenta"}
                </Button>
              </form>
            </>
          )}
        </div>
      </div>
    </AuthLayout>
  )
}
